(* ::Package:: *)

(* 本文件实现 018 的模板化连续指标撒点。DSSeeds 先生成完整离散态并执行
   EOM/canonical；本模块只展开 general 连续指标，并保留可供 DSLinear 审计的来源信息。 *)


(* ::Chapter:: *)
(*Seed 模板构造与完整性封装*)

If[! ValueQ[$dSIBPLastSeedTemplates], $dSIBPLastSeedTemplates = Missing["NotGenerated"]];
If[! ValueQ[$dSIBPLastSeedGroups], $dSIBPLastSeedGroups = Missing["NotGenerated"]];
If[! ValueQ[$dSIBPLastSeedGroupMetadata], $dSIBPLastSeedGroupMetadata = Missing["NotGenerated"]];


DSAllSeeds::noseeds = "尚未生成 seed 模板。请先成功调用 DSSeeds。 No seed templates are available. Run DSSeeds successfully first.";
DSAllSeeds::badseed = "输入不含 DSSeeds 生成的 allSeeds。 The input does not contain allSeeds generated by DSSeeds.";
DSSeedGroups::noseeds = "尚未生成分组 seed 模板。请先成功调用 DSSeeds。 No grouped seed templates are available. Run DSSeeds successfully first.";
DSSeedGroups::badseed = "输入不含 DSSeeds 生成的 seedGroups。 The input does not contain seedGroups generated by DSSeeds.";
DSSeedGroupMetadata::badseed = "输入不含 DSSeeds 生成的 seedGroupMetadata。 The input does not contain seedGroupMetadata generated by DSSeeds.";


dsTemplateSource[topo_Association, sectorKey_String, ibpClass_String, shrunkLines_List] := Which[
   sectorKeyTopQ[sectorKey, Lookup[topo, "ibpMode", "full"], Length[Lookup[topo, "lines", {}]]] && ibpClass === "qIBP", "momentum",
   sectorKeyTopQ[sectorKey, Lookup[topo, "ibpMode", "full"], Length[Lookup[topo, "lines", {}]]] && ibpClass === "tIBP", "time",
   ibpClass === "qIBP", {"shrinkSectorMomentum", shrunkLines},
   True, {"shrinkSectorTime", shrunkLines}
   ];


dsTemplateGeneratorLabel[generator_Association] := If[
   Lookup[generator, "type", "missing"] === "time",
   timeGeneratorLabel[generator],
   momentumGeneratorLabel[generator]
   ];


dsTemplateGeneratorClass[generator_Association] := If[
   Lookup[generator, "type", "missing"] === "time", "tIBP", "qIBP"
   ];


(* loop 模板只遍历离散 n=0,1，不代入任何连续指标。这样 EOM 在撒点前完成，
   而 a/b/ISP 仍能由 DSGenerateIBP 统一或逐指标展开。 *)
dsLoopTemplatesForTopology[topo_Association] := Module[
   {base, continuousIndices, discreteVariables, discreteData, generators, rawTemplates,
    sectorKey, shrunkLines, metadata, representation, records},
   base = makeBaseIntegral[topo];
   continuousIndices = continuousIndexVariables[base];
   discreteVariables = DeleteDuplicates[Cases[base, _n, Infinity]];
   discreteData = selectedDiscreteSeedRules[topo];
   If[Lookup[discreteData, "status", "failed"] =!= "generated",
    Return[<|"status" -> "failed", "reason" -> "discreteEnumerationFailed",
      "sectorKey" -> sectorKeyFromShrunkLines[topo, Lookup[topo, "sectorShrunkLines", {}]],
      "discreteData" -> discreteData|>]
    ];
   generators = Select[
     makeIBPGenerators[topo],
     Function[generator,
      Lookup[generator, "type", "missing"] === "time" ||
       Lookup[topo, "ibpMode", "full"] === "full"
      ]
     ];
   rawTemplates = Table[
     <|"generatorData" -> generator, "generator" -> dsTemplateGeneratorLabel[generator],
       "ibpClass" -> dsTemplateGeneratorClass[generator],
       "expression" -> If[
         Lookup[generator, "type", "missing"] === "time",
         applyTimeGeneratorSeed[topo, base, generator],
         applyMomentumGeneratorSeed[topo, base, generator]
         ]|>,
     {generator, generators}
     ];
   If[MemberQ[Lookup[rawTemplates, "expression", {}], $Failed],
    Return[<|"status" -> "failed", "reason" -> "generatorTemplateFailed"|>]
    ];
   shrunkLines = Lookup[topo, "sectorShrunkLines", {}];
   sectorKey = sectorKeyFromShrunkLines[topo, shrunkLines];
   metadata = Lookup[topo, "sectorMetadata", makeSectorMetadata[topo]];
   representation = If[
     Lookup[topo, "ibpMode", "full"] === "timeOnly",
     "J[timePowers,linePacks,isp]",
     "J[timePowers,indexedLinePacks,isp]"
     ];
   records = Flatten[
     Table[
      Module[{expr = applySeedCanonical[template["expression"] /. discreteRule, topo]},
       <|
        "source" -> dsTemplateSource[topo, sectorKey, template["ibpClass"], shrunkLines],
        "sectorKey" -> sectorKey,
        "sectorShrunkLines" -> shrunkLines,
        "sectorMetadata" -> metadata,
        "generator" -> template["generator"],
        "ibpClass" -> template["ibpClass"],
        "continuousIndices" -> continuousIndices,
        "sourceIntegral" -> (base /. discreteRule),
        "discreteVariables" -> discreteVariables,
        "discreteRules" -> discreteRule,
        "discreteStateCountExpected" -> discreteData["ruleCount"],
        "rawBinaryDiscreteStateCount" -> Lookup[
          discreteData, "rawBinaryStateCount", 2^Length[discreteVariables]
          ],
        "discreteSeedMode" -> Lookup[discreteData, "mode", "allBinaryStates"],
        "masslessCanonicalDirection" -> Lookup[
          discreteData, "canonicalDirection", Missing["NotApplicable"]
          ],
        "equation" -> Expand[expr],
        "forbiddenNData" -> forbiddenNData[topo, expr],
        "eomCanonicalQ" -> ! containsForbiddenNQ[topo, expr],
        "representation" -> representation,
        "ibpMode" -> Lookup[topo, "ibpMode", "full"]
        |>
       ],
      {template, rawTemplates}, {discreteRule, discreteData["rules"]}
      ],
     1
     ];
   <|
    "status" -> "generated",
    "sectorKey" -> sectorKey,
    "recordCount" -> Length[records],
    "discreteVariables" -> discreteVariables,
    "discreteStateCount" -> Length[discreteData["rules"]],
    "rawBinaryDiscreteStateCount" -> Lookup[
      discreteData, "rawBinaryStateCount", 2^Length[discreteVariables]
      ],
    "eliminatedAlgebraicStateCount" -> Lookup[
      discreteData, "eliminatedAlgebraicStateCount", 0
      ],
    "discreteSeedMode" -> Lookup[discreteData, "mode", "allBinaryStates"],
    "masslessCanonicalDirection" -> Lookup[
      discreteData, "canonicalDirection", Missing["NotApplicable"]
      ],
    "allSeeds" -> records
    |>
   ];


dsLoopSeedTemplateData[context_Association, seedData_Association] := Module[
   {rootTopo, metadataList, shrunkLists, topologies, pieces, bad, records},
   rootTopo = context["topology"];
   metadataList = Lookup[seedData, "sectorMetadataList", {makeSectorMetadata[rootTopo]}];
   shrunkLists = DeleteCases[Lookup[metadataList, "sectorShrunkLines", {}], {}];
   topologies = Join[{rootTopo}, shrinkSectorTopology[rootTopo, #] & /@ shrunkLists];
   pieces = dsLoopTemplatesForTopology /@ topologies;
   bad = Select[pieces, Lookup[#, "status", "failed"] =!= "generated" &];
   If[bad =!= {}, Return[<|"status" -> "failed", "reason" -> "sectorTemplateFailed", "failures" -> bad|>]];
   records = Flatten[Lookup[pieces, "allSeeds", {}], Infinity];
   <|"status" -> "generated", "allSeeds" -> records, "sectorCount" -> Length[pieces],
     "templateCount" -> Length[records],
     "discreteStateAudits" -> (KeyTake[#, {
           "sectorKey", "discreteVariables", "discreteStateCount",
           "rawBinaryDiscreteStateCount", "eliminatedAlgebraicStateCount",
           "discreteSeedMode", "masslessCanonicalDirection"
           }] & /@ pieces)|>
   ];


makeAllSeedTemplateData[context_Association, seedData_Association] :=
   dsLoopSeedTemplateData[context, seedData];


dsSeedTemplateHashPayload[records_List] := KeyDrop[
    #,
    {"templateHash", "templateSetHash", "templateOrdinal", "templateCount", "contextInputHash", "caseName"}
    ] & /@ records;


dsSeedTemplateRecordHash[record_Association] := IntegerString[
   Hash[First[dsSeedTemplateHashPayload[{record}]], "SHA256"],
   16,
   64
   ];


dsSealSeedTemplates[records_List, context_Association] := Module[{flat, payload, hash, count},
   flat = Flatten[records, Infinity];
   count = Length[flat];
   payload = dsSeedTemplateHashPayload[flat];
   hash = IntegerString[Hash[payload, "SHA256"], 16, 64];
   MapIndexed[
    Join[#1, <|"templateHash" -> dsSeedTemplateRecordHash[#1],
       "templateSetHash" -> hash, "templateOrdinal" -> First[#2],
       "templateCount" -> count, "contextInputHash" -> context["inputHash"],
       "caseName" -> context["caseName"]|>] &,
    flat
    ]
   ];


DSAllSeeds[seedData_Association] := Module[{seeds = Lookup[seedData, "allSeeds", Missing["NotFound"]]},
   If[! ListQ[seeds], Message[DSAllSeeds::badseed]; dsErrorPrint[
      "输入中没有可用的 allSeeds。 No usable allSeeds field was found in the input."
      ]; Return[$Failed]];
   seeds
   ];


DSAllSeeds[] := If[
   ListQ[$dSIBPLastSeedTemplates],
   $dSIBPLastSeedTemplates,
   Message[DSAllSeeds::noseeds];
   dsErrorPrint["尚无 seed 模板。 No seed templates have been generated."];
   $Failed
   ];


DSSeedGroups[seedData_Association] := Module[{groups = Lookup[seedData, "seedGroups", Missing["NotFound"]]},
   If[! ListQ[groups], Message[DSSeedGroups::badseed]; dsErrorPrint[
      "输入中没有可用的 seedGroups。 No usable seedGroups field was found in the input."
      ]; Return[$Failed]];
   groups
   ];


DSSeedGroups[] := If[
   ListQ[$dSIBPLastSeedGroups],
   $dSIBPLastSeedGroups,
   Message[DSSeedGroups::noseeds];
   dsErrorPrint["尚无分组 seed 模板。 No grouped seed templates have been generated."];
   $Failed
   ];


DSSeedGroupMetadata[seedData_Association] := Module[
   {metadata = Lookup[seedData, "seedGroupMetadata", Missing["NotFound"]]},
   If[! ListQ[metadata], Message[DSSeedGroupMetadata::badseed]; dsErrorPrint[
      "输入中没有可用的 seedGroupMetadata。 No usable seedGroupMetadata field was found in the input."
      ]; Return[$Failed]];
   metadata
   ];


DSSeedGroupMetadata[] := If[
   ListQ[$dSIBPLastSeedGroupMetadata],
   $dSIBPLastSeedGroupMetadata,
   Message[DSSeedGroups::noseeds];
   dsErrorPrint["尚无 seed 分组说明。 No seed-group metadata have been generated."];
   $Failed
   ];


(* ::Chapter:: *)
(*连续指标提取与范围门禁*)

DSGenerateIBP::badseeds = "seeds 必须是 DSSeeds 生成的模板列表或含 J 的表达式列表。 seeds must be a template list generated by DSSeeds or a list of expressions containing J.";
DSGenerateIBP::badrange = "撒点范围格式或整数边界无效：`1`。 The sampling range format or integer bounds are invalid: `1`.";
DSGenerateIBP::coverage = "精细范围没有精确覆盖模板指标：`1`。 Detailed ranges do not exactly cover the template indices: `1`.";
DSGenerateIBP::discrete = "n_i 是已在模板阶段遍历的离散指标，不得再次撒点：`1`。 n_i are discrete indices already enumerated in the template stage and must not be sampled again: `1`.";
DSGenerateIBP::symbolicn = "模板仍含符号 n_i，说明离散态/EOM 阶段未完成：`1`。 Symbolic n_i remain in the templates, so discrete-state enumeration or EOM canonicalization is incomplete: `1`.";
DSGenerateIBP::integrity = "seed 模板完整性检查失败：`1`。 Seed-template integrity validation failed: `1`.";
Options[DSGenerateIBP] = {AuditLevel -> "standard", ProgressReporting -> Automatic};
Options[generateIBP] = Options[DSGenerateIBP];
$dsMetaSeedRangeState = Missing["NotInitialized"];


dsSeedTemplateEntries[seeds_] := Flatten[{seeds}, Infinity];


(* 公开坐标模板在撒点前只投影一次。canonical 若重新引入底层原子，才需要在该点
   再投影；该判定只跳过恒等变换，不改变任何代数或 sector 规则。 *)
dsInternalCoordinatePresentQ018[expr_] := ! FreeQ[
   expr,
   _qq | _qk | _kk | _z | _xi | _rho | _externalLegSquaredCoordinate
   ];


dsSeedTemplateEquation[entry_Association] := Lookup[entry, "equation", Lookup[entry, "treeSeed", Missing["NoEquation"]]];
dsSeedTemplateEquation[entry_] := entry;


dsContinuousIndicesFromIntegral[J[aList_, linePacks_, ispList_]] := DeleteDuplicates@Join[
    Quiet@Check[Variables[Flatten[{aList}]], Cases[aList, _a, Infinity]],
    DeleteDuplicates[Cases[linePacks, _b | _bS, Infinity]],
    Quiet@Check[Variables[Flatten[{ispList}]], Flatten[{ispList}]]
    ];
dsSeedTemplateContinuousIndices[entries_List] := Module[{declared, inferred},
   declared = DeleteDuplicates@Flatten[Lookup[Select[entries, AssociationQ], "continuousIndices", {}], Infinity];
   inferred = DeleteDuplicates@Flatten[
      dsContinuousIndicesFromIntegral /@ DeleteDuplicates[Cases[dsSeedTemplateEquation /@ entries, _J, Infinity]],
      Infinity
      ];
   DeleteDuplicates@Join[declared, inferred]
   ];


dsSeedTemplateSymbolicN[entries_List] := DeleteDuplicates[Cases[dsSeedTemplateEquation /@ entries, _n, Infinity]];


(* ::Chapter:: *)
(*Seed shift metadata 初始化*)

(* 每个积分先把全部参数 Flatten 成同一种数据面，再用 Variables 发现指标；这里不读取
   aList/linePacks/ispList 的位置或 pack 长度，因此 sector 表示变化不影响 shift 提取。 *)
dsFlattenSeedIntegralData[expr_] := Cases[
   expr,
   HoldPattern[J[args___]] :> Flatten[{args}],
   Infinity
   ];


dsVariablesFromFlattenedSeedData[data_List] := DeleteDuplicates@Quiet@Check[
    Variables[DeleteCases[Flatten[data], _String]],
    {}
    ];


dsEntrySeedVariables[entry_] := Module[{equation, source},
   equation = dsSeedTemplateEquation[entry];
   source = If[AssociationQ[entry], Lookup[entry, "sourceIntegral", Missing["NoSource"]], Missing["NoSource"]];
   dsVariablesFromFlattenedSeedData@Join[
     dsFlattenSeedIntegralData[equation],
     If[Head[source] === J, dsFlattenSeedIntegralData[source], {}]
     ]
   ];


dsSeedMetadataHash[entries_List] := IntegerString[
   Hash[HoldComplete[dsSeedTemplateEquation /@ entries], "SHA256"],
   16,
   64
   ];


(* DSSeeds 的推荐层次按物理生成元分组；用户仍可把 flat allSeeds 作为一个总组传入。 *)
dsSeedSourceDescriptor[entry_] := With[
   {
    sectorKey = If[AssociationQ[entry], Lookup[entry, "sectorKey", Missing["sectorKey"]], Missing["sectorKey"]],
    ibpClass = If[AssociationQ[entry], Lookup[entry, "ibpClass", "unknownIBP"], "unknownIBP"],
    generator = If[AssociationQ[entry], Lookup[entry, "generator", Missing["generator"]], Missing["generator"]]
    },
   HoldComplete[sectorKey, ibpClass, generator]
   ];


dsDefaultSeedGroups[records_List] := GatherBy[records, dsSeedSourceDescriptor];


dsSeedGroupMetadataFromGroups[groups_List] := MapIndexed[
   Function[{group, position}, <|
     "groupOrdinal" -> First[position],
     "sourceDescriptors" -> DeleteDuplicates[dsSeedSourceDescriptor /@ group],
     "sectorKeys" -> DeleteDuplicates[Lookup[Select[group, AssociationQ], "sectorKey", {}]],
     "ibpClasses" -> DeleteDuplicates[Lookup[Select[group, AssociationQ], "ibpClass", {}]],
     "generators" -> DeleteDuplicates[Lookup[Select[group, AssociationQ], "generator", {}]],
     "templateOrdinals" -> Lookup[Select[group, AssociationQ], "templateOrdinal", {}],
     "templateCount" -> Length[group]
     |>],
   groups
   ];


(* flat 输入整体统计；存在二级或更深列表时只认最外层分组，每组内部任意深度 Flatten。 *)
dsMetaSeedInputGroups[seeds_] := Module[{top},
   top = If[ListQ[seeds], seeds, {seeds}];
   If[AnyTrue[top, ListQ], dsSeedTemplateEntries /@ top, {dsSeedTemplateEntries[top]}]
   ];


dsMetaSeedGroupRecord[templateRecords_List] := Module[
   {indices, shiftData, shiftBounds, seedRangeOffsets, first, descriptors},
   first = First[templateRecords];
   descriptors = DeleteDuplicates[Lookup[templateRecords, "sourceDescriptor", {}]];
   indices = DeleteDuplicates[Flatten[Lookup[templateRecords, "continuousIndices", {}]]];
   shiftData = Association@Table[
      index -> DeleteDuplicates@Flatten[
        Table[Lookup[Lookup[record, "shiftData", <||>], index, {}], {record, templateRecords}]
        ],
      {index, indices}
      ];
   shiftBounds = Association@KeyValueMap[
      #1 -> If[#2 === {}, Missing["NoAffineShift"], {Min[#2], Max[#2]}] &,
      shiftData
      ];
   seedRangeOffsets = Association@KeyValueMap[
      #1 -> If[ListQ[#2], {-First[#2], -Last[#2]}, Missing["NoAffineShift"]] &,
      shiftBounds
      ];
   <|
    "groupOrdinal" -> first["groupOrdinal"],
    "groupKey" -> With[{ordinal = first["groupOrdinal"]}, HoldComplete["inputGroup", ordinal]],
    "sourceDescriptors" -> descriptors,
    "sectorKeys" -> DeleteDuplicates[Lookup[templateRecords, "sectorKey", {}]],
    "ibpClasses" -> DeleteDuplicates[Lookup[templateRecords, "ibpClass", {}]],
    "generators" -> DeleteDuplicates[Lookup[templateRecords, "generator", {}]],
    "templateCount" -> Length[templateRecords],
    "templateOrdinals" -> Lookup[templateRecords, "templateOrdinal", {}],
    "continuousIndices" -> indices,
    "shiftData" -> Normal[shiftData],
    "shiftBounds" -> Normal[shiftBounds],
    "seedRangeOffsets" -> Normal[seedRangeOffsets]
    |>
   ];


DSMetaSeedRange::badseeds = "seeds 必须是 DSSeeds 生成的模板列表或含 J 的表达式列表。 seeds must be a template list generated by DSSeeds or a list of expressions containing J.";
DSMetaSeedRange::badindices = "指标声明必须是一个变量列表：`1`。 The index declaration must be a list of variables: `1`.";


(* 用户声明只用于审计预期集合；metadata 始终按 seed 中实际发现的完整变量集建立。
   再次成功调用会整体覆盖旧状态，避免不同 family 的 shift 数据混用。 *)
DSMetaSeedRange[seeds_, declaredIndices_List] := Module[
   {inputGroups, groupingMode, entries, groupOrdinals, badEntries, declared,
    entryVariables, discovered, missing, extra, records, groups, state},
   inputGroups = dsMetaSeedInputGroups[seeds];
   groupingMode = If[Length[inputGroups] === 1 && ! AnyTrue[If[ListQ[seeds], seeds, {seeds}], ListQ],
     "flatOverall", "topLevelGroups"];
   entries = Flatten[inputGroups, 1];
   groupOrdinals = Flatten@MapIndexed[ConstantArray[First[#2], Length[#1]] &, inputGroups];
   badEntries = Select[
     entries,
     Function[entry,
      With[{equation = dsSeedTemplateEquation[entry]},
       Head[equation] === Missing || (! TrueQ[equation === 0] && FreeQ[equation, _J])
       ]
      ]
     ];
   If[entries === {} || badEntries =!= {},
    Message[DSMetaSeedRange::badseeds];
    dsErrorPrint["无法初始化 seed shift metadata。 Failed to initialize seed-shift metadata."];
    Return[<|"status" -> "failed", "reason" -> "invalidSeeds", "invalidEntries" -> badEntries|>]
    ];
   declared = DeleteDuplicates[Flatten[{declaredIndices}]];
   If[! VectorQ[declared, Not@*NumericQ],
    Message[DSMetaSeedRange::badindices, declaredIndices];
    dsErrorPrint["指标声明包含数值或不是一维变量列表。 The index declaration contains numbers or is not a flat variable list."];
    Return[<|"status" -> "failed", "reason" -> "invalidIndexDeclaration"|>]
    ];
   entryVariables = dsEntrySeedVariables /@ entries;
   discovered = DeleteDuplicates[Flatten[entryVariables]];
   missing = Complement[discovered, declared];
   extra = Complement[declared, discovered];
   If[missing =!= {},
    dsWarningPrint[
     "声明遗漏了实际 seed 指标；初始化将自动补入：" <> ToString[missing, InputForm] <>
      ". The declaration omitted actual seed indices; initialization will add them: " <>
      ToString[missing, InputForm]
     ]
    ];
   If[extra =!= {},
    dsWarningPrint[
     "声明含有 seed 中不存在的指标；它们不会参与撒点：" <> ToString[extra, InputForm] <>
      ". The declaration contains indices absent from the seeds; they will not be sampled: " <>
      ToString[extra, InputForm]
     ]
    ];
   records = MapThread[
     Function[{entry, variables, groupOrdinal, templatePosition}, <|
       "groupOrdinal" -> groupOrdinal,
       "groupKey" -> With[{ordinal = groupOrdinal}, HoldComplete["inputGroup", ordinal]],
       "sourceDescriptor" -> dsSeedSourceDescriptor[entry],
        "sectorKey" -> If[AssociationQ[entry], Lookup[entry, "sectorKey", Missing["sectorKey"]], Missing["sectorKey"]],
       "ibpClass" -> If[AssociationQ[entry], Lookup[entry, "ibpClass", "unknownIBP"], "unknownIBP"],
       "generator" -> If[AssociationQ[entry], Lookup[entry, "generator", Missing["generator"]], Missing["generator"]],
       "templateOrdinal" -> If[AssociationQ[entry], Lookup[entry, "templateOrdinal", Missing["templateOrdinal"]], Missing["templateOrdinal"]],
       "templatePosition" -> templatePosition,
       "continuousIndices" -> variables,
       "shiftData" -> Association@Table[index -> dsSeedIndexShifts[entry, index], {index, variables}]
       |>],
     {entries, entryVariables, groupOrdinals, Range[Length[entries]]}
     ];
   groups = dsMetaSeedGroupRecord /@ GatherBy[records, Lookup[#, "groupOrdinal"] &];
   state = <|
     "status" -> "initialized",
     "seedHash" -> dsSeedMetadataHash[entries],
     "templateCount" -> Length[entries],
     "inputGroupingMode" -> groupingMode,
     "groupingRule" -> "flat list -> one group; nested list -> flatten each top-level item as one group",
     "declaredIndices" -> declared,
     "discoveredIndices" -> discovered,
     "missingIndices" -> missing,
     "extraIndices" -> extra,
     "declarationExactQ" -> (missing === {} && extra === {}),
     "records" -> records,
     "groups" -> groups
     |>;
   $dsMetaSeedRangeState = state;
   dsInfoPrint[
    "分组规则：flat seeds 整体统计；nested seeds 按最外层逐组 Flatten 后统计。本次共 " <>
     ToString[Length[groups]] <> " 组。 Grouping rule: flat seeds are analyzed as one group; " <>
     "nested seeds are flattened and analyzed per top-level item. This call created " <>
     ToString[Length[groups]] <> " groups."
    ];
   dsInfoPrint[
    "已初始化 " <>
     ToString[Length[records]] <> " 条 seed shift metadata；后续初始化会覆盖本状态。 " <>
     "Initialized seed-shift metadata for " <> ToString[Length[records]] <>
     " templates; a later initialization will replace this state."
    ];
   state
   ];


DSMetaSeedRange[seeds_, declared_] := (
   Message[DSMetaSeedRange::badindices, declared];
   dsErrorPrint["第二个参数必须是指标列表。 The second argument must be an index list."];
   <|"status" -> "failed", "reason" -> "invalidIndexDeclaration"|>
   );


DSMetaSeedRange[] := $dsMetaSeedRangeState;


metaSeedRange[args___] := DSMetaSeedRange[args];


dsSeedTemplateIntegrityAudit[entries_List, auditLevel_String] := Module[
   {records, hashes, counts, ordinals, expectedHash, payload, actualHash,
     declaredCount, ordinalQ, recordHashQ, completeSetQ, passQ},
   records = Select[entries, AssociationQ];
   If[Length[records] =!= Length[entries],
    Return[<|"status" -> "unsealed", "passQ" -> False, "reason" -> "rawExpressions"|>]
    ];
   hashes = DeleteDuplicates[Lookup[records, "templateSetHash", Missing["MissingHash"]]];
   counts = DeleteDuplicates[Lookup[records, "templateCount", Missing["MissingCount"]]];
   ordinals = Lookup[records, "templateOrdinal", Missing["MissingOrdinal"]];
   If[Length[hashes] =!= 1 || Length[counts] =!= 1 || ! IntegerQ[First[counts]],
    Return[<|"status" -> "failed", "passQ" -> False, "reason" -> "metadataMismatch",
      "hashes" -> hashes, "counts" -> counts, "ordinals" -> ordinals|>]
   ];
   declaredCount = First[counts];
   ordinalQ = DuplicateFreeQ[ordinals] && And @@ (IntegerQ[#] && 1 <= # <= declaredCount & /@ ordinals);
   recordHashQ = If[
     auditLevel === "full",
     And @@ Map[
       Function[record,
        Lookup[record, "templateHash", Missing["MissingTemplateHash"]] ===
         dsSeedTemplateRecordHash[record]
        ],
       records
       ],
     Missing["ProducerMetadataTrustedAtStandardAuditLevel"]
     ];
   If[! TrueQ[ordinalQ] || TrueQ[recordHashQ === False],
     Return[<|"status" -> "failed", "passQ" -> False, "reason" -> "recordIntegrityMismatch",
       "declaredTemplateCount" -> declaredCount, "ordinals" -> ordinals,
       "ordinalQ" -> ordinalQ, "recordHashQ" -> recordHashQ|>]
     ];
   expectedHash = First[hashes];
   completeSetQ = Length[records] === declaredCount && ordinals === Range[declaredCount];
   actualHash = If[
     auditLevel === "full" && completeSetQ,
     payload = dsSeedTemplateHashPayload[records];
     IntegerString[Hash[payload, "SHA256"], 16, 64],
     Missing["NotRecomputedAtStandardAuditLevel"]
     ];
   passQ = TrueQ[ordinalQ && (auditLevel =!= "full" ||
        (recordHashQ && (! completeSetQ || expectedHash === actualHash)))];
   <|"status" -> Which[
      ! passQ, "failed",
      completeSetQ, "sealedComplete",
      True, "sealedSubset"
      ],
      "passQ" -> passQ, "sealedQ" -> passQ, "completeSetQ" -> completeSetQ,
      "auditLevel" -> auditLevel,
      "expectedHash" -> expectedHash, "actualHash" -> actualHash,
     "declaredTemplateCount" -> declaredCount, "templateCount" -> Length[records],
     "templateOrdinals" -> ordinals|>
   ];


dsRangePairQ[spec_] := MatchQ[spec, {_Integer, _Integer}] && spec[[1]] <= spec[[2]];


dsRangeSpecificationAudit[indices_List, specs_List] := Module[
   {uniformQ, detailedQ, normalizedSpecs, groupedSpecs, conflictingAliases,
    variables, duplicate, unknown, missing, discrete, invalid},
   uniformQ = Length[specs] === 1 && dsRangePairQ[First[specs]];
   detailedQ = specs =!= {} && And @@ (MatchQ[#, {_, _Integer, _Integer}] & /@ specs);
   If[uniformQ,
    Return[<|"status" -> "passed", "mode" -> "uniform", "variables" -> indices,
      "rangeRules" -> Thread[indices -> ConstantArray[First[specs], Length[indices]]],
      "unknownIndices" -> {}, "missingIndices" -> {}, "duplicateIndices" -> {},
      "discreteIndicesInRangeSpec" -> {}, "invalidRanges" -> {}|>]
    ];
   If[! detailedQ,
    Return[<|"status" -> "failed", "reason" -> "invalidRangeShape", "invalidRanges" -> specs|>]
    ];
   normalizedSpecs = ({dsRootEnvelopeIndex[First[#]], #[[2]], #[[3]]} &) /@ specs;
   groupedSpecs = GatherBy[normalizedSpecs, First];
   conflictingAliases = Select[
     groupedSpecs,
     Length[DeleteDuplicates[#[[All, 2 ;; 3]]]] > 1 &
     ];
   normalizedSpecs = First /@ groupedSpecs;
   variables = First /@ normalizedSpecs;
   duplicate = Cases[Tally[variables], {var_, count_} /; count > 1 :> var];
   discrete = Select[variables, MatchQ[#, _n] &];
   unknown = Select[variables, Function[var, ! AnyTrue[indices, SameQ[#, var] &] && ! MatchQ[var, _n]]];
   missing = Select[indices, Function[var, ! AnyTrue[variables, SameQ[#, var] &]]];
   invalid = Join[Select[normalizedSpecs, #[[2]] > #[[3]] &], conflictingAliases];
   <|
    "status" -> If[Join[duplicate, discrete, unknown, missing, invalid] === {}, "passed", "failed"],
    "mode" -> "detailed",
    "variables" -> indices,
    "rangeRules" -> If[Join[duplicate, discrete, unknown, missing, invalid] === {},
      (#[[1]] -> #[[2 ;; 3]]) & /@ normalizedSpecs, {}],
    "unknownIndices" -> unknown,
    "missingIndices" -> missing,
    "duplicateIndices" -> duplicate,
    "discreteIndicesInRangeSpec" -> discrete,
    "invalidRanges" -> invalid
    |>
   ];


(* shrink sector 的 bS[e] 继承 root top 的 b[e] 目标包络。用户只需描述 root
   指标域；sector-specific seed 区间由模板中的实际 shift 自动反推。 *)
dsRootEnvelopeIndex[index_] := index /. HoldPattern[bS[e_]] :> b[e];


dsRootEnvelopeIndices[indices_List] := DeleteDuplicates[dsRootEnvelopeIndex /@ indices];


dsSeedIndexShifts[entry_, index_] := Module[{equation, values, shifts},
   equation = dsSeedTemplateEquation[entry];
   If[TrueQ[equation === 0], Return[{0}]];
   values = Flatten[dsFlattenSeedIntegralData[equation]];
   shifts = DeleteDuplicates@Cases[
      values,
      value_ /; IntegerQ[Expand[value - index]] :> Expand[value - index]
      ];
   shifts
   ];


(* 要求组内所有 shifted indices 都落在 [L,U]，故 seed 点域取各 shift 逆像的
   交集 [L-Min[Delta],U-Max[Delta]]；作用后所得关系的外包络刚好回到 [L,U]。 *)
dsDerivedSeedRangeAudit[group_Association, targetRanges_Association] := Module[
   {indices, missingTargets, shiftBounds, missingShifts, rawSeedRules, seedRules},
   indices = Lookup[group, "continuousIndices", {}];
   missingTargets = Select[
     indices,
     ! KeyExistsQ[targetRanges, dsRootEnvelopeIndex[#]] &
     ];
   shiftBounds = Association[Lookup[group, "shiftBounds", {}]];
   missingShifts = Select[indices, ! ListQ[Lookup[shiftBounds, #, Missing["NoAffineShift"]]] &];
   If[Join[missingTargets, missingShifts] =!= {},
    Return[<|
      "status" -> "failed",
      "reason" -> "seedEnvelopeInferenceFailed",
      "groupOrdinal" -> Lookup[group, "groupOrdinal", Missing["groupOrdinal"]],
      "groupKey" -> Lookup[group, "groupKey", Missing["groupKey"]],
      "sourceDescriptors" -> Lookup[group, "sourceDescriptors", {}],
      "missingTargetIndices" -> missingTargets,
      "indicesWithoutAffineShifts" -> missingShifts
      |>]
    ];
   rawSeedRules = Table[
     With[
      {target = targetRanges[dsRootEnvelopeIndex[index]], bounds = shiftBounds[index]},
      index -> {First[target] - First[bounds], Last[target] - Last[bounds]}
      ],
     {index, indices}
     ];
   (* 自动反推不得把 ISP seed 下界降到用户 target 下界以下；用户显式给出的负下界
      保持有效，package 只避免为了覆盖升幂项而自行再向更负方向扩张。 *)
   seedRules = rawSeedRules /. HoldPattern[(index_ -> range_List)] /; MatchQ[index, _ispN] :>
      index -> {Max[First[targetRanges[index]], First[range]], Last[range]};
   <|
    "status" -> "passed",
    "groupOrdinal" -> Lookup[group, "groupOrdinal", Missing["groupOrdinal"]],
    "groupKey" -> Lookup[group, "groupKey", Missing["groupKey"]],
    "sourceDescriptors" -> Lookup[group, "sourceDescriptors", {}],
    "ibpClasses" -> Lookup[group, "ibpClasses", {}],
    "templateCount" -> Lookup[group, "templateCount", 0],
    "continuousIndices" -> indices,
    "shiftBounds" -> Normal[shiftBounds],
    "seedRangeOffsets" -> Lookup[group, "seedRangeOffsets", {}],
    "unclippedSeedRangeRules" -> rawSeedRules,
    "seedRangeRules" -> seedRules,
    "emptySeedDomainQ" -> AnyTrue[Last /@ seedRules, First[#] > Last[#] &]
    |>
   ];


dsSeedRangeRuleText[rules_List] := StringRiffle[
   ToString[{First[#], Sequence @@ Last[#]}, InputForm] & /@ rules,
   ", "
   ];


dsSeedRangeSourceText[audit_Association] := ToString[
   Lookup[audit, "sourceDescriptors", {}],
   InputForm
   ];


dsReportDerivedSeedRanges[rangeAudits_List, setting_: Automatic] := Module[
   {ordinal, rules, source, empty},
   Do[
    ordinal = Lookup[audit, "groupOrdinal", Missing["groupOrdinal"]];
    rules = Lookup[audit, "seedRangeRules", {}];
    source = dsSeedRangeSourceText[audit];
    dsInfoPrint[
     "编号 " <> ToString[ordinal] <> "（来源 " <> source <> "）：" <>
      dsSeedRangeRuleText[rules] <> ". Group " <> ToString[ordinal] <>
      " (source " <> source <> "): " <> dsSeedRangeRuleText[rules] <> ".",
     setting
     ],
    {audit, rangeAudits}
    ];
   empty = Select[rangeAudits, TrueQ[Lookup[#, "emptySeedDomainQ", False]] &];
   If[empty =!= {},
    dsWarningPrint[
     "以下分组的目标包络窄于该组 shift 跨度，因此不存在能使所有移位后积分仍落在目标包络内的 seed 点：" <>
      StringRiffle[
       ("编号 " <> ToString[Lookup[#, "groupOrdinal", Missing["groupOrdinal"]]] <>
          "（来源 " <> dsSeedRangeSourceText[#] <> "）：" <>
          dsSeedRangeRuleText[Lookup[#, "seedRangeRules", {}]]) & /@ empty,
       "; "
       ] <> "。这些编号的 IBP 撒点结果为空；最终方程集合缺少对应关系，不能作为完整约化系统。 " <>
       "For the following groups, the target envelope is narrower than the group shift span, so no seed point can keep every shifted integral inside the target envelope: " <>
       StringRiffle[
       ("group " <> ToString[Lookup[#, "groupOrdinal", Missing["groupOrdinal"]]] <>
          " (source " <> dsSeedRangeSourceText[#] <> "): " <>
          dsSeedRangeRuleText[Lookup[#, "seedRangeRules", {}]]) & /@ empty,
       "; "
       ] <> ". IBP sampling is empty for these groups; the final equation set lacks their relations and cannot be used as a complete reduction system.",
     setting
     ]
    ];
   empty
   ];


(* ::Chapter:: *)
(*公开连续撒点入口*)

dsGeneratedIBPSectorSummaries[records_List, ibpMode_String, rootLineCount_Integer?NonNegative] := Module[{sectorKeys},
   sectorKeys = Select[
     DeleteDuplicates[Lookup[records, "sectorKey", {}]],
     StringQ[#] && ! sectorKeyTopQ[#, ibpMode, rootLineCount] &
     ];
   Table[
    With[{sectorRecords = Select[records, Lookup[#, "sectorKey", None] === sectorKey &]},
     <|
      "sectorKey" -> sectorKey,
      "sectorShrunkLines" -> Lookup[First[sectorRecords], "sectorShrunkLines", {}],
      "momentumSummary" -> <|"generators" -> DeleteDuplicates[Lookup[Select[sectorRecords, Lookup[#, "ibpClass", None] === "qIBP" &], "generator", {}]]|>,
      "timeSummary" -> <|"generators" -> DeleteDuplicates[Lookup[Select[sectorRecords, Lookup[#, "ibpClass", None] === "tIBP" &], "generator", {}]]|>
      |>
     ],
    {sectorKey, sectorKeys}
    ]
   ];


dsGeneratedIBPSourceDigest[records_List, context_Association, rangeAudit_Association] := Module[{payload},
   payload = {
     Lookup[context, "inputHash", Missing["inputHash"]],
     Lookup[rangeAudit, "rangeRules", {}],
     KeyTake[#, {"sectorKey", "ibpClass", "generator", "continuousRules", "equation"}] & /@ records
     };
   IntegerString[Hash[payload, "SHA256"], 16, 64]
   ];


dsGeneratedIBPArtifactContract[
   records_List,
   context_Association,
   rangeAudit_Association,
   integrityAudit_Association,
   completeCanonicalQ_,
   auditLevel_String
   ] := Module[{sealedQ, completeSystemQ},
   sealedQ = TrueQ[Lookup[integrityAudit, "sealedQ", False]];
   completeSystemQ = TrueQ[
     sealedQ && Lookup[integrityAudit, "completeSetQ", False] && completeCanonicalQ
     ];
   <|
    "contractVersion" -> 1,
    "sealedQ" -> sealedQ,
    "sourceDigest" -> dsGeneratedIBPSourceDigest[records, context, rangeAudit],
    "completeSystemQ" -> completeSystemQ,
    "subsetQ" -> TrueQ[sealedQ && ! Lookup[integrityAudit, "completeSetQ", False]],
    "auditLevel" -> auditLevel,
    "capabilities" -> <|
      "linearizeQ" -> True,
      "formalReductionQ" -> completeSystemQ,
      "reuseProducerCanonicalQ" -> sealedQ
      |>
    |>
   ];


dsGeneratedIBPBatch[records_List, templates_List, context_Association, rangeAudit_Association,
   integrityAudit_Association, derivedRangeAudits_List, metaState_Association] := Module[
    {topRecords, metadataList, forbidden, eomQ, representation, ibpMode, templateHash,
     templateRecords, firstTemplate, emptyRangeAudits, emptyMomentumQ, emptyTimeQ,
     numericRulesAppliedBeforeSeeds, seedNumericRules, seedCoefficientVariables,
     sampledCoefficientVariables, rootLineCount, invalidSectorKeys},
    templateRecords = Select[templates, AssociationQ];
   firstTemplate = If[templateRecords === {}, Missing["RawExpressionTemplates"], First[templateRecords]];
   (* subset 仍需继承完整 sector schema；模板子集只改变关系覆盖，不改变 topology 身份。 *)
   metadataList = context["sectors"];
   forbidden = DeleteCases[Flatten[Lookup[records, "forbiddenNData", {}]], Null];
   eomQ = And @@ Lookup[records, "eomCanonicalQ", {False}];
   representation = If[Head[firstTemplate] === Missing,
     "J[timePowers,indexedLinePacks,isp]",
     Lookup[firstTemplate, "representation", "J[timePowers,indexedLinePacks,isp]"]
     ];
    ibpMode = If[Head[firstTemplate] === Missing,
      Lookup[context["topology"], "ibpMode", "full"],
      Lookup[firstTemplate, "ibpMode", Lookup[context["topology"], "ibpMode", "full"]]
      ];
    rootLineCount = Length[Lookup[context["topology"], "lines", {}]];
    invalidSectorKeys = Select[
      DeleteDuplicates[Lookup[records, "sectorKey", Missing["sectorKey"]]],
      ! sectorKeyForModeQ[#, ibpMode, rootLineCount] &
      ];
    If[invalidSectorKeys =!= {},
     Return[<|
       "status" -> "failed",
       "reason" -> "invalidSectorKeyForMode",
       "ibpMode" -> ibpMode,
       "rootLineCount" -> rootLineCount,
       "invalidSectorKeys" -> invalidSectorKeys,
       "equations" -> records
       |>]
     ];
    topRecords = Select[
      records,
      sectorKeyTopQ[Lookup[#, "sectorKey", Missing["sectorKey"]], ibpMode, rootLineCount] &
      ];
   templateHash = If[Head[firstTemplate] === Missing,
     Missing["UnsealedTemplates"],
     Lookup[firstTemplate, "templateSetHash", Missing["UnsealedTemplates"]]
     ];
   emptyRangeAudits = Select[derivedRangeAudits, TrueQ[Lookup[#, "emptySeedDomainQ", False]] &];
   emptyMomentumQ = AnyTrue[emptyRangeAudits, MemberQ[Lookup[#, "ibpClasses", {}], "qIBP"] &];
   emptyTimeQ = AnyTrue[emptyRangeAudits, MemberQ[Lookup[#, "ibpClasses", {}], "tIBP"] &];
   numericRulesAppliedBeforeSeeds = TrueQ[
     templateRecords =!= {} && And @@ Lookup[templateRecords, "numericRulesAppliedBeforeSeeds", False]
     ];
   seedNumericRules = If[numericRulesAppliedBeforeSeeds,
     Lookup[firstTemplate, "seedNumericRules", {}], {}];
   seedCoefficientVariables = If[numericRulesAppliedBeforeSeeds,
     DeleteDuplicates[Flatten[Lookup[templateRecords, "seedCoefficientVariables", {}]]], {}];
   sampledCoefficientVariables = If[numericRulesAppliedBeforeSeeds,
     DeleteDuplicates[Flatten[Lookup[records, "sampledCoefficientVariables", {}]]], {}];
   <|
    "status" -> "generated",
    "dSIBPStatus" -> "generated",
    "generationRoute" -> "DSGenerateIBP",
    "caseName" -> context["caseName"],
    "ibpMode" -> ibpMode,
    "representation" -> representation,
    "topologyValidationReport" -> context["validationReport"],
    "sectorMetadata" -> First[metadataList],
    "sectorMetadataList" -> metadataList,
    "momentumSummary" -> <|"generators" -> DeleteDuplicates[Lookup[Select[topRecords, Lookup[#, "ibpClass", None] === "qIBP" &], "generator", {}]]|>,
    "timeSummary" -> <|"generators" -> DeleteDuplicates[Lookup[Select[topRecords, Lookup[#, "ibpClass", None] === "tIBP" &], "generator", {}]]|>,
     "shrinkSectorSummary" -> <|
       "sectorSummaries" -> dsGeneratedIBPSectorSummaries[records, ibpMode, rootLineCount]
       |>,
    "equationCount" -> Length[records],
    "eomCanonicalQ" -> eomQ,
    "forbiddenNData" -> forbidden,
    "pendingFeatures" -> {},
    "completeMomentumIBPQ" -> TrueQ[ibpMode === "full" && ! emptyMomentumQ],
    "completeTimeIBPQ" -> ! emptyTimeQ,
    "completeCanonicalQ" -> TrueQ[eomQ && forbidden === {} && emptyRangeAudits === {}],
    "allSeeds" -> templates,
    "templateSetHash" -> templateHash,
    "templateIntegrityAudit" -> integrityAudit,
    "continuousIndices" -> rangeAudit["variables"],
    "rangeMode" -> "targetEnvelope",
    "targetEnvelopeMode" -> rangeAudit["mode"],
    "targetEnvelopeRules" -> rangeAudit["rangeRules"],
    "derivedSeedRangeAudits" -> derivedRangeAudits,
    "emptySeedRangeGroups" -> emptyRangeAudits,
    "seedRangeMetadata" -> KeyDrop[metaState, "records"],
    "candidatePointCount" -> Total[Function[item,
        Lookup[item, "templateCount", 0] *
         Times @@ (Max[0, Last[#] - First[#] + 1] & /@ (Last /@ Lookup[item, "seedRangeRules", {}]))
        ] /@ derivedRangeAudits],
    "parityAcceptedPointCount" -> Length[records],
    "equations" -> records,
    "dSIBPContextSummary" -> dsContextSummary[context],
    "numericRulesAppliedBeforeSeeds" -> numericRulesAppliedBeforeSeeds,
    "seedNumericRules" -> seedNumericRules,
    "seedCoefficientVariables" -> seedCoefficientVariables,
    "sampledCoefficientVariables" -> sampledCoefficientVariables
    |>
   ];


DSGenerateIBP[seeds_, specs__List, OptionsPattern[]] := Module[
   {entries, badEntries, indices, symbolicN, audit, integrity, context, hashes,
    envelopeIndices, specList, targetRangeAssociation, metaState, metaHash,
    derivedRangeAudits, derivedRangeByGroup, entryGroupOrdinals, failedRangeAudits,
    progress, records, sectorTopologyCache, postSamplingCanonicalRequiredQ,
    pointRulesByGroup, parityPointRulesCache,
    parityCertificate, batch, artifactContract, auditLevel = OptionValue[AuditLevel]},
   If[! MemberQ[{"standard", "full"}, auditLevel],
    Return[<|"status" -> "failed", "reason" -> "invalidAuditLevel",
      "auditLevel" -> auditLevel, "allowedAuditLevels" -> {"standard", "full"}|>]
    ];
   entries = dsSeedTemplateEntries[seeds];
   (* EOM/canonical 可以把某个完整离散态模板化为精确零；密封模板中的 0 仍是合法恒等式。
      非零且不含 J 的表达式继续拒绝，避免把任意常数列表误当作 IBP 模板。 *)
   badEntries = Select[
     entries,
     Function[entry,
      With[{equation = dsSeedTemplateEquation[entry]},
       Head[equation] === Missing || (! TrueQ[equation === 0] && FreeQ[equation, _J])
       ]
      ]
     ];
   If[entries === {} || badEntries =!= {},
    Message[DSGenerateIBP::badseeds];
    dsErrorPrint["seeds 不是可展开的 IBP 模板列表。 seeds is not an expandable IBP-template list."];
    Return[<|"status" -> "failed", "reason" -> "invalidSeeds", "invalidEntries" -> badEntries|>]
    ];
   symbolicN = dsSeedTemplateSymbolicN[entries];
   If[symbolicN =!= {},
    Message[DSGenerateIBP::symbolicn, symbolicN];
    dsErrorPrint["模板必须先完整遍历 n_i=0,1 并执行 EOM。 Templates must enumerate n_i=0,1 and apply EOM first."];
    Return[<|"status" -> "failed", "reason" -> "symbolicDiscreteIndices", "symbolicDiscreteIndices" -> symbolicN|>]
    ];
   metaHash = dsSeedMetadataHash[entries];
   metaState = If[
     AssociationQ[$dsMetaSeedRangeState] &&
      Lookup[$dsMetaSeedRangeState, "status", "failed"] === "initialized" &&
      Lookup[$dsMetaSeedRangeState, "seedHash", None] === metaHash,
     $dsMetaSeedRangeState,
     DSMetaSeedRange[entries, DeleteDuplicates[Flatten[dsEntrySeedVariables /@ entries]]]
     ];
   If[Lookup[metaState, "status", "failed"] =!= "initialized",
    Return[<|"status" -> "failed", "reason" -> "seedMetadataInitializationFailed",
      "seedMetadata" -> metaState|>]
    ];
   indices = Lookup[metaState, "discoveredIndices", {}];
   envelopeIndices = dsRootEnvelopeIndices[indices];
   specList = {specs};
   audit = dsRangeSpecificationAudit[envelopeIndices, specList];
   If[Lookup[audit, "discreteIndicesInRangeSpec", {}] =!= {},
    Message[DSGenerateIBP::discrete, audit["discreteIndicesInRangeSpec"]];
    dsErrorPrint["n_i 不属于连续撒点范围。 n_i are not continuous sampling indices."];
    Return[Join[audit, <|"status" -> "failed", "reason" -> "discreteIndexInRangeSpec"|>]]
    ];
   If[Lookup[audit, "status", "failed"] =!= "passed",
    If[Lookup[audit, "reason", None] === "invalidRangeShape",
     Message[DSGenerateIBP::badrange, Lookup[audit, "invalidRanges", {specs}]],
     Message[DSGenerateIBP::coverage, KeyTake[audit, {"unknownIndices", "missingIndices", "duplicateIndices", "invalidRanges"}]]
     ];
    dsErrorPrint["请修正范围格式并完整覆盖所有连续指标。 Correct the ranges and cover every continuous index exactly once."];
    Return[Join[audit, <|"status" -> "failed", "reason" -> Lookup[audit, "reason", "rangeCoverageFailed"]|>]]
    ];
   integrity = dsSeedTemplateIntegrityAudit[entries, auditLevel];
   If[AssociationQ[First[entries]] && ! TrueQ[Lookup[integrity, "passQ", False]],
    Message[DSGenerateIBP::integrity, integrity];
    dsErrorPrint["模板集合被删改或不完整。 The template set was modified or is incomplete."];
    Return[<|"status" -> "failed", "reason" -> "templateIntegrityFailed", "templateIntegrityAudit" -> integrity|>]
    ];
   context = dsResolveContext[Automatic];
   hashes = DeleteDuplicates[Lookup[Select[entries, AssociationQ], "contextInputHash", {}]];
   If[Head[context] === Missing || (hashes =!= {} && hashes =!= {context["inputHash"]}),
    dsErrorPrint["当前 DSInit context 与模板不同源。 The current DSInit context does not match the templates."];
    Return[<|"status" -> "failed", "reason" -> "contextMismatch", "templateContextHashes" -> hashes|>]
    ];
   sectorTopologyCache = sectorTopologyCache018[context["topology"], context["sectors"]];
   If[Head[sectorTopologyCache] === Missing,
    dsErrorPrint["sector topology 缓存初始化失败。 Failed to initialize the sector-topology cache."];
    Return[<|"status" -> "failed", "reason" -> "sectorTopologyCacheFailed",
      "cacheFailure" -> sectorTopologyCache|>]
    ];
   postSamplingCanonicalRequiredQ =
    sectorCachePostSamplingCanonicalRequiredQ018[sectorTopologyCache];
   targetRangeAssociation = Association[audit["rangeRules"]];
   derivedRangeAudits = dsDerivedSeedRangeAudit[#, targetRangeAssociation] & /@
     Lookup[metaState, "groups", {}];
   failedRangeAudits = Select[derivedRangeAudits, Lookup[#, "status", "failed"] =!= "passed" &];
   If[failedRangeAudits =!= {},
    dsErrorPrint["无法从目标积分包络反推全部 seed 点域。 Failed to infer every seed domain from the target integral envelope."];
    Return[<|"status" -> "failed", "reason" -> "seedEnvelopeInferenceFailed",
      "failures" -> failedRangeAudits|>]
    ];
   dsReportDerivedSeedRanges[derivedRangeAudits, OptionValue[ProgressReporting]];
   derivedRangeByGroup = AssociationThread[
     Lookup[derivedRangeAudits, "groupOrdinal", {}],
     derivedRangeAudits
     ];
   (* 同一 group 的连续点域由相同的反推范围决定。这里一次性构造后复用，避免每个
      离散态 template 重复建立相同 Tuples；空区间仍自然得到空点域。 *)
   pointRulesByGroup = Association@Map[
      Function[rangeData,
       With[
        {ordinal = Lookup[rangeData, "groupOrdinal", Missing["groupOrdinal"]],
         groupIndices = Lookup[rangeData, "continuousIndices", {}],
         valueLists = (Range @@ Last[#]) & /@ Lookup[rangeData, "seedRangeRules", {}]},
        ordinal -> If[groupIndices === {}, {{}}, Thread[groupIndices -> #] & /@ Tuples[valueLists]]
        ]
       ],
      derivedRangeAudits
      ];
   (* parity 预筛只依赖 group 点域、sector metadata 与 source integral 的仿射 parity
      signature。同 signature 的不同生成元 template 共享筛点结果。 *)
   parityPointRulesCache = <||>;
   entryGroupOrdinals = Lookup[Lookup[metaState, "records", {}], "groupOrdinal", {}];
   progress = OptionValue[ProgressReporting];
   records = dsProgressMap[
      "正在展开连续 IBP 指标 / Expanding continuous IBP indices",
      MapThread[{#1, #2} &, {entries, entryGroupOrdinals}],
       Function[item,
          Module[{entry = First[item], groupOrdinal = Last[item], entryRangeAudit,
            pointRules, parityCacheKey, parityMetadata, paritySource, paritySignature,
            entryPointRules, templateEquation, canonicalTemplateEquation,
            templateForbiddenNData, templateEOMCanonicalQ, expression,
            numericRulesAppliedBeforeSeeds, seedNumericRules,
            sampledCoefficientVariables, updated},
        entryRangeAudit = Lookup[
          derivedRangeByGroup,
          groupOrdinal,
          <|"status" -> "failed", "reason" -> "missingGeneratorGroup"|>
          ];
         pointRules = Lookup[pointRulesByGroup, groupOrdinal, {}];
         parityMetadata = If[AssociationQ[entry], Lookup[entry, "sectorMetadata", Missing["NoSectorMetadata"]], Missing["NoSectorMetadata"]];
         paritySource = If[AssociationQ[entry], Lookup[entry, "sourceIntegral", Missing["NoSourceIntegral"]], Missing["NoSourceIntegral"]];
         paritySignature = If[
           AssociationQ[parityMetadata] && Head[paritySource] === J,
           parityIntegralSignature018[parityMetadata, paritySource],
           Missing["NoParitySignature"]
           ];
         parityCacheKey = HoldComplete[
           groupOrdinal,
           If[AssociationQ[parityMetadata], Lookup[parityMetadata, "sectorKey", Missing["sectorKey"]], Missing["sectorKey"]],
           paritySignature
           ];
         entryPointRules = If[
           KeyExistsQ[parityPointRulesCache, parityCacheKey],
           parityPointRulesCache[parityCacheKey],
           With[{filtered = dsParityFilteredPointRules018[entry, pointRules, context]},
            AssociateTo[parityPointRulesCache, parityCacheKey -> filtered];
            filtered
            ]
           ];
        templateEquation = dsLoopSeedExpressionToPublicCoordinates[
          dsSeedTemplateEquation[entry],
          context["topology"]
          ];
        canonicalTemplateEquation = sectorAwareCanonical018[
          templateEquation,
          context["topology"],
          sectorTopologyCache
          ];
        canonicalTemplateEquation = If[
          canonicalTemplateEquation === $Failed ||
           ! dsInternalCoordinatePresentQ018[canonicalTemplateEquation],
          canonicalTemplateEquation,
          dsLoopSeedExpressionToPublicCoordinates[
           canonicalTemplateEquation,
           context["topology"]
           ]
          ];
        templateForbiddenNData = forbiddenNData[
          context["topology"],
          canonicalTemplateEquation
          ];
         templateEOMCanonicalQ = FreeQ[canonicalTemplateEquation, _n];
         numericRulesAppliedBeforeSeeds = TrueQ[
           AssociationQ[entry] && Lookup[entry, "numericRulesAppliedBeforeSeeds", False]
           ];
         seedNumericRules = If[
           numericRulesAppliedBeforeSeeds,
           Lookup[entry, "seedNumericRules", {}],
           {}
           ];
         Table[
          expression = canonicalTemplateEquation /. rules;
         If[postSamplingCanonicalRequiredQ,
          (* general template 已完成 EOM 与 target-sector endpoint canonical；具体整数点
             只需补做可能依赖连续指标值的用户/tadpole symmetry。 *)
          expression = sectorAwareSymmetry018[
            Expand[expression],
            context["topology"],
            sectorTopologyCache
            ];
          (* 数值依赖 symmetry 可能重新引入内部 Gram 原子；只在这条兼容路线重投影。 *)
          expression = If[
            expression === $Failed || ! dsInternalCoordinatePresentQ018[expression],
            expression,
            dsLoopSeedExpressionToPublicCoordinates[expression, context["topology"]]
             ]
           ];
          (* parity 先筛点，连续指标随后取值，用户给出的有序 symmetry 再把每项送到
             唯一代表。最后重复应用同一精确数值规则并逐项约分，保证 symmetry 产生的
             新系数也在进入 linearData 前完成实数/数值化。 *)
          If[numericRulesAppliedBeforeSeeds,
           expression = dsNumericSeedExpression018[expression, seedNumericRules]
           ];
          sampledCoefficientVariables = If[
            numericRulesAppliedBeforeSeeds,
            dsSeedCoefficientVariables018[expression],
            {}
            ];
          updated = If[AssociationQ[entry], Join[entry, <|
              "continuousRules" -> rules,
              "seedRangeGroupOrdinal" -> groupOrdinal,
              "targetEnvelopeRules" -> audit["rangeRules"],
              "derivedSeedRangeRules" -> entryRangeAudit["seedRangeRules"],
               "templateCandidatePointCount" -> Length[pointRules],
               "sampledCoefficientVariables" -> sampledCoefficientVariables,
               "equation" -> expression,
              "forbiddenNData" -> If[postSamplingCanonicalRequiredQ,
                forbiddenNData[context["topology"], expression], templateForbiddenNData],
              "eomCanonicalQ" -> If[postSamplingCanonicalRequiredQ,
                FreeQ[expression, _n], templateEOMCanonicalQ]
              |>],
           <|"source" -> "userTemplate",
             "sectorKey" -> sectorKeyFromShrunkLines[context["topology"], {}],
             "generator" -> Missing["NotAvailable"],
             "ibpClass" -> "unknownIBP", "continuousRules" -> rules,
             "seedRangeGroupOrdinal" -> groupOrdinal,
             "targetEnvelopeRules" -> audit["rangeRules"],
              "derivedSeedRangeRules" -> entryRangeAudit["seedRangeRules"],
              "templateCandidatePointCount" -> Length[pointRules],
              "sampledCoefficientVariables" -> sampledCoefficientVariables,
              "equation" -> expression,
             "forbiddenNData" -> If[postSamplingCanonicalRequiredQ,
               forbiddenNData[context["topology"], expression], templateForbiddenNData],
             "eomCanonicalQ" -> If[postSamplingCanonicalRequiredQ,
               FreeQ[expression, _n], templateEOMCanonicalQ]|>];
         If[AssociationQ[entry] && KeyExistsQ[entry, "treeSeed"], updated = Join[updated, <|"treeSeed" -> expression|>]];
         updated,
         {rules, entryPointRules}
         ]
        ]
       ],
      progress
      ] // Flatten[#, 1] &;
   dsInfoPrint[
    "已生成 " <> ToString[Length[records]] <> " 条 IBP 方程。 Generated " <>
     ToString[Length[records]] <> " IBP equations.", progress
    ];
   parityCertificate = If[
     auditLevel === "full" || ! TrueQ[Lookup[integrity, "sealedQ", False]],
     dsParityCertificate018[records, context],
     <|
      "status" -> "producerGuaranteed",
      "passQ" -> True,
      "auditLevel" -> auditLevel,
      "reason" -> "sealed templates were parity-prefiltered and sector-canonicalized by DSGenerateIBP"
      |>
     ];
   If[! TrueQ[Lookup[parityCertificate, "passQ", False]],
    dsErrorPrint["生成后的 parity certificate 失败；未删除任何积分或关系。 The post-generation parity certificate failed; no integral or equation was deleted."];
    Return[<|"status" -> "failed", "reason" -> "parityCertificateFailed",
      "parityCertificate" -> parityCertificate, "equations" -> records|>]
    ];
   batch = dsGeneratedIBPBatch[records, entries, context, audit, integrity, derivedRangeAudits, metaState];
   artifactContract = dsGeneratedIBPArtifactContract[
     records,
     context,
     audit,
     integrity,
     Lookup[batch, "completeCanonicalQ", False],
     auditLevel
     ];
   Join[batch, <|
     "completeSystemQ" -> artifactContract["completeSystemQ"],
     "artifactContract" -> artifactContract,
     "parityCertificate" -> parityCertificate
     |>]
   ];


DSGenerateIBP[seeds_, ___] := (
   Message[DSGenerateIBP::badrange, "expected {min,max} or {index,min,max},..."];
   dsErrorPrint["调用格式应为 {min,max} 或完整的 {index,min,max},...。 Use {min,max} or a complete sequence of {index,min,max},...."];
   <|"status" -> "failed", "reason" -> "invalidCall"|>
   );


generateIBP[args___] := DSGenerateIBP[args];
