(* ::Package:: *)

(* 本文件集中冻结 023 的运行时 Message 文本。所有消息逐句先中文、后英文；
   只覆盖展示字符串，不改变任何 status、reason、capability 或返回数据。 *)


(* ::Chapter:: *)
(*高层 workflow 消息*)

DSInit::badinput = "DSInit 无法解析当前 topology，或 ISP/动量坐标不能闭合函数族。请按现行 topology 格式修正输入并重新初始化。 DSInit could not parse the topology, or its ISP/momentum coordinates do not close the family. Correct the input using the current topology schema and initialize again.";
DSInit::sectorincomplete = "无法完整初始化所有可由 contact 到达的 sector：`1`。请检查传播子端点和缩并规则后重新初始化。 Not all contact-reachable sectors could be initialized: `1`. Check propagator endpoints and contraction rules, then initialize again.";
DSInit::initconflict = "初始化目录 `1` 已含不同输入哈希或未知文件；如确认覆盖，请显式设置 OverwriteInitialization -> True。 Initialization directory `1` contains a different input hash or unknown files. Set OverwriteInitialization -> True explicitly only if these files may be replaced.";
DSInit::writefailed = "初始化 metadata 无法写入 `1`。请检查输出路径、路径长度和写入权限后重试。 Initialization metadata could not be written to `1`. Check the output path, path length, and write permission, then try again.";
DSInfo::noinit = "当前没有已注册的 DSInit context。请先成功调用 DSInit。 No DSInit context is currently registered. Run DSInit successfully first.";
DSInfo::badcontext = "给定对象不是有效的 DSInit context。请传入 DSInit 成功返回的 context。 The supplied object is not a valid DSInit context. Pass a context returned by a successful DSInit call.";

DSSeeds::noinit = "DSSeeds 需要有效的 DSInit context。请先成功调用 DSInit，并把返回值传给 DSSeeds。 DSSeeds requires a valid DSInit context. Run DSInit successfully and pass its result to DSSeeds.";
DSSeeds::failed = "seed 模板未能生成。结构化详情为 `1`；请检查 topology、sector 和离散态输入后重试。 Seed templates could not be generated. Structured details: `1`. Check the topology, sectors, and discrete-state input, then try again.";
DSSeeds::capability = "当前 context 不支持 seed 生成。结构化详情为 `1`；请查看 context 的 capabilities 并修正初始化输入。 The current context does not support seed generation. Structured details: `1`. Inspect the context capabilities and correct the initialization input.";
DSLinear::noinit = "DSLinear 需要有效的 DSInit context。请传入与 seedData 同一次 DSInit 返回的 context。 DSLinear requires a valid DSInit context. Pass the context from the same DSInit call as seedData.";
DSLinear::badseed = "DSLinear 只接受 DSSeeds 或 DSGenerateIBP 成功返回的 seedData。请先生成 seed，再调用 DSLinear。 DSLinear accepts only seedData returned by a successful DSSeeds or DSGenerateIBP call. Generate seeds before calling DSLinear.";
DSLinear::badmode = "LinearSystemMode 只允许 \"symbolic\" 或 \"numeric\"，收到 `1`。请选择其中一种模式后重试。 LinearSystemMode must be \"symbolic\" or \"numeric\"; received `1`. Choose one of these modes and try again.";
DSLinear::failed = "线性方程数据未能生成。结构化详情为 `1`；请检查 seed 完整性和数值规则后重试。 Linear-equation data could not be generated. Structured details: `1`. Check seed integrity and numeric rules, then try again.";
DSLinear::capability = "当前 context 不支持生成 linearData。结构化详情为 `1`；请查看 capabilities 并修正初始化输入。 The current context does not support linearData generation. Structured details: `1`. Inspect its capabilities and correct the initialization input.";
DSLinear::context = "seedData 与 context 不是同一次初始化的产物。请使用生成该 seedData 的原始 context。 seedData and context do not originate from the same initialization. Use the original context that produced this seedData.";

DSAllSeeds::noseeds = "当前没有 seed 模板。请先成功调用 DSSeeds。 No seed templates are available. Run DSSeeds successfully first.";
DSAllSeeds::badseed = "输入中没有 DSSeeds 生成的 allSeeds。请传入完整 seedData。 The input does not contain allSeeds generated by DSSeeds. Pass complete seedData.";
DSSeedGroups::noseeds = "当前没有分组 seed 模板。请先成功调用 DSSeeds。 No grouped seed templates are available. Run DSSeeds successfully first.";
DSSeedGroups::badseed = "输入中没有 DSSeeds 生成的 seedGroups。请传入完整 seedData。 The input does not contain seedGroups generated by DSSeeds. Pass complete seedData.";
DSSeedGroupMetadata::badseed = "输入中没有与 seedGroups 同源的分组 metadata。请传入完整 seedData。 The input does not contain grouping metadata from the same source as seedGroups. Pass complete seedData.";
DSMetaSeedRange::badseeds = "无法从当前输入识别 seed 模板。请传入 DSSeeds 结果或含 J 的表达式列表。 Seed templates could not be recognized in the input. Pass a DSSeeds result or a list of expressions containing J.";
DSMetaSeedRange::badindices = "指标声明必须是变量列表，收到 `1`。请列出需要统计移位的连续指标。 The index declaration must be a list of variables; received `1`. List the continuous indices whose shifts should be analyzed.";
DSGenerateIBP::badseeds = "无法从当前输入识别 seed 模板。请传入 DSSeeds 结果或含 J 的表达式列表。 Seed templates could not be recognized in the input. Pass a DSSeeds result or a list of expressions containing J.";
DSGenerateIBP::badrange = "撒点范围的格式或整数边界无效：`1`。请使用统一 {min,max} 或逐指标范围。 The sampling range has an invalid format or noninteger bound: `1`. Use a common {min,max} range or one explicit range per index.";
DSGenerateIBP::coverage = "逐指标范围没有精确覆盖模板中的连续指标：`1`。请补齐缺失指标并删除多余项。 Per-index ranges do not exactly cover the continuous template indices: `1`. Add missing indices and remove extra entries.";
DSGenerateIBP::discrete = "离散态 n 已在模板阶段枚举，不应再次撒点：`1`。请只给连续 a、b 和 ISP 指标范围。 Discrete n states are already enumerated at the template stage and must not be sampled again: `1`. Specify ranges only for continuous a, b, and ISP indices.";
DSGenerateIBP::symbolicn = "模板中仍有未取值的离散态 n：`1`。请重新生成完整 DSSeeds 结果后再撒点。 Symbolic discrete n states remain in the templates: `1`. Regenerate complete DSSeeds data before sampling.";
DSGenerateIBP::integrity = "seed 模板完整性检查失败：`1`。请重新生成同源模板，不要混合不同 context 的 seed。 Seed-template integrity validation failed: `1`. Regenerate same-source templates and do not mix seeds from different contexts.";

DSKiraPlan::badlinear = "DSKiraPlan 只接受 DSLinear 成功返回的 linearData。请先生成同源线性方程数据。 DSKiraPlan accepts only linearData returned by a successful DSLinear call. Generate same-source linear-equation data first.";
DSKiraPlan::badspec = "Kira 计划配置无效：`1`。请检查 targets、active basis 和导数变量。 The Kira-plan specification is invalid: `1`. Check targets, the active basis, and derivative variables.";
DSKiraPlan::badstage = "Kira 计划阶段只允许 \"preReduction\" 或 \"formal\"，收到 `1`。请选择其中一个阶段。 The Kira-plan stage must be \"preReduction\" or \"formal\"; received `1`. Choose one of these stages.";
DSKiraPlan::badbasis = "formal 计划的 active basis 或一阶导数闭包无效：`1`。请修正 basis 后重新生成计划。 The active basis or first-derivative closure for the formal plan is invalid: `1`. Correct the basis and regenerate the plan.";
DSKiraPlan::incomplete = "formal Kira 计划需要 completeSystemQ=True 的 linearData。请先补齐关系并重新调用 DSLinear。 A formal Kira plan requires linearData with completeSystemQ=True. Complete the relations and run DSLinear again.";
DSReorderIntegrals::badlinear = "DSReorderIntegrals 只接受 DSLinear 成功返回的 linearData。请传入同源数据。 DSReorderIntegrals accepts only linearData returned by a successful DSLinear call. Pass same-source data.";
DSReorderIntegrals::badorder = "积分顺序必须是由现有 J 或积分 ID 组成的非空列表。请从 linearData 的 integralList 中选择。 The integral order must be a nonempty list of existing J objects or integral IDs. Choose entries from linearData integralList.";
DSUserMI::badlinear = "DSUserMI 只接受尚未附加 userMI 的有效 linearData。请使用 DSLinear 的原始结果。 DSUserMI accepts only valid linearData that does not already contain userMI data. Use the original DSLinear result.";
DSUserMI::badbasis = "userMI basis 无效：`1`。请检查表达式独立性、顺序和 activeIndices。 The userMI basis is invalid: `1`. Check expression independence, ordering, and activeIndices.";

DSKiraExport::badlinear = "DSKiraExport 只接受 DSLinear 成功返回的 backend-neutral linearData。请先生成同源线性方程数据。 DSKiraExport accepts only backend-neutral linearData returned by a successful DSLinear call. Generate same-source linear-equation data first.";
DSKiraExport::failed = "Kira 输入未能生成。结构化详情为 `1`；请检查返回的 reason 和输入目录后重试。 Kira input could not be generated. Structured details: `1`. Inspect the returned reason and input directory, then try again.";
DSKiraExport::badbasis = "KiraActiveBasis 未通过验证。结构化详情为 `1`；请修正 basis 和导数 target closure。 KiraActiveBasis failed validation. Structured details: `1`. Correct the basis and derivative-target closure.";
DSKiraExport::capability = "linearData 没有通过同源能力门禁。请使用同一 context 的 DSLinear 结果，并确认 backendExportUsableQ=True。 linearData did not pass the same-source capability gate. Use a DSLinear result from the same context and confirm backendExportUsableQ=True.";
DSKiraExport::devarrules = "数值或系数规则与微分阶段合同冲突，Kira 导出已拒绝：`1`。请在解析导数和 target closure 生成前保留微分变量。 Numeric or coefficient rules conflict with the differentiation-stage contract, so Kira export was rejected: `1`. Preserve the differentiation variables until analytic derivatives and target closure have been generated.";
DSKiraExport::badstage = "KiraNumericStage 只允许 \"symbolic\" 或 \"postDerivative\"，收到 `1`。请按导数是否已解析生成选择阶段。 KiraNumericStage must be \"symbolic\" or \"postDerivative\"; received `1`. Choose the stage according to whether analytic derivatives have already been generated.";
DSKiraExport::incomplete = "当前方程集没有通过完整性检查，不能用于正式 Kira 约化。请补齐目标积分所需的关系后重新生成 linearData。 The current equation set did not pass the completeness check and cannot be used for a formal Kira reduction. Add the relations required by the target integrals and regenerate linearData.";
DSKiraExport::writefailed = "Kira manifest 无法写入 `1`。请检查输出目录、路径长度和写入权限后重试。 The Kira manifest could not be written to `1`. Check the output directory, path length, and write permission, then try again.";

DSKiraImport::badpath = "Kira workspace 路径不存在或不是目录：`1`。请传入本次 DSKiraExport 对应的 workspace。 The Kira workspace path does not exist or is not a directory: `1`. Pass the workspace corresponding to the current DSKiraExport call.";
DSKiraImport::missing = "Kira 结果缺少必需文件：`1`。请完成约化或恢复缺失文件后再导入。 Required Kira result files are missing: `1`. Complete the reduction or restore the missing files before importing.";
DSKiraImport::incomplete = "Kira 完成日志没有成功标记：`1`。请检查 Kira 日志和约化状态；结构闭合门禁仍会独立执行。 The Kira completion log has no success marker: `1`. Inspect the Kira log and reduction status; structural closure gates still run independently.";
DSKiraImport::mismatch = "Kira 结果与当前 export 或 context 不一致。结构化详情为 `1`；请使用同一次导出和初始化产生的文件。 Kira results do not match the current export or context. Structured details: `1`. Use files produced by the same export and initialization.";
DSKiraImport::invalid = "Kira reduction 数据未通过完整性检查。结构化详情为 `1`；请检查映射、masters 和约化表后重新运行。 Kira reduction data failed its integrity check. Structured details: `1`. Check maps, masters, and the reduction table, then rerun the reduction.";

DSDE::badreduction = "DSDE 只接受 DSKiraImport 验证通过的 reductionData。请先成功导入同源 Kira 结果。 DSDE accepts only reductionData validated by DSKiraImport. Import matching Kira results successfully first.";
DSDE::badvars = "微分变量必须来自当前 family 已初始化的外部独立变量列表：`1`。请从该列表中选择变量后重试。 Differentiation variables must come from the initialized independent external-variable list of the current family: `1`. Choose variables from this list and try again.";
DSDE::notclosed = "微分方程没有闭合到选定的主积分。未闭合变量为 `1`，残留对象数为 `2`。请补齐这些对象的约化规则后重新运行 DSDE。 The differential equations did not close on the selected master integrals. Unclosed variables: `1`; residual-object count: `2`. Add reduction rules for these objects and run DSDE again.";
DSDE::writefailed = "DE 结果无法写入 `1`。请检查输出路径、路径长度和写入权限；内存返回值仍保留实际计算状态。 DE results could not be written to `1`. Check the output path, path length, and write permission; the in-memory return value still retains the actual calculation status.";
DSScaleCheck::badde = "DSScaleCheck 只接受 DSDE 返回的 generated DE 数据。请先补齐约化并生成闭合 DE。 DSScaleCheck accepts only generated DE data returned by DSDE. Complete the reduction and generate a closed DE first.";
DSScaleCheck::badspec = "标度 relation、variables、weights 或 degrees 不完整，或相应列表长度不一致：`1`。请补齐这些字段并使列表长度一致后重试。 The scaling relation, variables, weights, or degrees are incomplete, or their list lengths are inconsistent: `1`. Complete these fields, make the list lengths consistent, and try again.";
DSScaleCheck::failed = "标度关系未通过。证书范围为 `1`，矩阵和源项分别有 `2` 与 `3` 个非零残留。请检查标度次数、变量权重和微分方程后重新运行。 The scaling relation failed. Certificate scope: `1`; the matrix and source contain `2` and `3` nonzero residuals. Check the scaling degrees, variable weights, and differential equations, then run the check again.";


(* ::Chapter:: *)
(*底层 seed、坐标与 serializer 消息*)

parseTopology::missingkeys = "topology 缺少必需字段：`1`。请按当前输入格式补齐这些字段。 The topology is missing required fields: `1`. Add these fields using the current input schema.";
parseTopology::badinput = "topology 输入检查失败：`1`。请修正所列字段后重新初始化。 Topology input validation failed: `1`. Correct the listed fields and initialize again.";
parseTopology::badfunction = "massive line 的函数系统无法编译：`1`。请检查 P、Q、T、W 和变量定义。 A massive-line function system could not be compiled: `1`. Check its P, Q, T, W, and variable definitions.";
parseTopology::badsectorkey = "sectorKey 与当前 ibpMode 或 root line 顺序不一致：`1`。请使用初始化 metadata 给出的定长 key。 sectorKey is inconsistent with the current ibpMode or root-line order: `1`. Use the fixed-width key stored in initialization metadata.";
makeLinePack::badtype = "line `2` 的内部状态无法识别：`1`。请重新生成同源 sector 数据，不要手工构造 line pack。 The internal state of line `2` is not recognized: `1`. Regenerate same-source sector data instead of constructing a line pack manually.";
assertNoForbiddenN::badn = "离散态约化后仍残留不允许的 n 指标：`1`。请重新生成 seed；若问题重复出现，请连同 topology 报告此错误。 Forbidden n indices remain after discrete-state reduction: `1`. Regenerate the seeds; if the problem persists, report it together with the topology.";
symmetry::badrules = "symmetryRules 必须是 Rule 或 RuleDelayed 的列表。请修正列表格式后重试。 symmetryRules must be a list of Rule or RuleDelayed expressions. Correct the list format and try again.";

applyMomentumGeneratorSeed::nosp = "拓扑 `1` 没有唯一标量积反解，无法生成圈动量 IBP seed：`2`。请补齐独立动力学坐标。 Topology `1` has no unique scalar-product inverse, so a loop-momentum IBP seed cannot be generated: `2`. Complete the independent kinematic coordinates.";
applyTimeGeneratorSeed::badgen = "时间 IBP seed 收到了非时间生成元：`1`。请使用当前 context 列出的 dtau 生成元。 A time-IBP seed received a non-time generator: `1`. Use a dtau generator listed by the current context.";
applyExternalVectorDerivativeSeed::badgen = "外动量矢量 seed 收到了错误生成元：`1`。请使用当前 context 列出的 externalVector 生成元。 An external-vector seed received an invalid generator: `1`. Use an externalVector generator listed by the current context.";
applyExternalVectorDerivativeSeed::nosp = "拓扑 `1` 没有唯一标量积反解，无法生成外动量矢量 seed：`2`。请补齐独立动力学坐标。 Topology `1` has no unique scalar-product inverse, so an external-vector seed cannot be generated: `2`. Complete the independent kinematic coordinates.";
makeExternalInvariantDerivativeDecomposition::badvar = "变量 `1` 不是当前 context 的外部独立变量。请从初始化返回的变量列表中选择。 Variable `1` is not an independent external variable of the current context. Choose a variable from the initialized list.";
makeExternalInvariantDerivativeDecomposition::nosol = "变量 `1` 无法由外动量矢量导数基 `2` 唯一分解。请重选独立变量或修正动量声明。 Variable `1` cannot be decomposed uniquely in the external-vector derivative basis `2`. Choose independent variables again or correct the momentum declaration.";
makeKiraExportData::notlinearinput = "Kira 导出不能直接使用 seed batch：`1`。请先调用 DSLinear。 Kira export cannot consume a seed batch directly: `1`. Run DSLinear first.";
makeKiraExportData::badlinear = "当前线性方程不能导出到 Kira：`1`。请检查完整性、系数域和积分映射。 The current linear equations cannot be exported to Kira: `1`. Check completeness, the coefficient domain, and integral maps.";

dSIBPPublicAPI::notopo = "当前没有已注册的 topology context。请先成功调用 DSInit，或把 context 显式传给当前函数。 No topology context is currently registered. Run DSInit successfully or pass a context explicitly to the current function.";
dSIBPPublicAPI::badtopo = "topology context 无效或解析失败：`1`。请传入 DSInit 成功返回的 context。 The topology context is invalid or failed to parse: `1`. Pass a context returned by a successful DSInit call.";
dSIBPPublicAPI::badshape = "表达式中的 J 与当前 topology 不兼容：`1`。请使用该 context 生成的积分表示。 J objects in the expression are incompatible with the current topology: `1`. Use the integral representation generated by this context.";
dSIBPPublicAPI::badstate = "full line 的离散态必须显式为 0 或 1：`1`。请先使用 DSSeeds 完成离散态枚举。 Discrete states of every full line must be explicitly 0 or 1: `1`. Run DSSeeds to enumerate discrete states first.";
dSIBPPublicAPI::badgen = "当前 context 中没有请求的 IBP 生成元：`1`。请从 context 的生成元列表中选择。 The requested IBP generator is absent from the current context: `1`. Choose one from the context generator list.";
dSIBPPublicAPI::badvar = "变量 `1` 不在当前 topology 的外部独立变量列表 `2` 中。请从列表中选择或重新定义完整坐标。 Variable `1` is not in the initialized independent external-variable list `2`. Choose a listed variable or redefine a complete coordinate set.";
dSIBPPublicAPI::ambiguousvar = "变量 `1` 属于过完备动力学坐标，ds 已禁用。请先用 DSRedefineParameters 选择一组独立变量。 Variable `1` belongs to overcomplete kinematic coordinates, so ds is disabled. Choose an independent set with DSRedefineParameters first.";
dSIBPPublicAPI::noinverse = "当前动力学规则没有唯一的用户坐标到基础标量积反向映射，rep2innerform 已拒绝。审计详情：`1`。请重选独立坐标。 The current kinematic rules have no unique inverse map from user coordinates to base scalar products, so rep2innerform was rejected. Audit details: `1`. Choose independent coordinates again.";
dSIBPPublicAPI::nonlinear = "ds 只接受 J 的线性组合；当前表达式含非线性或非多项式 J 依赖：`1`。请先把表达式化为线性积分组合。 ds accepts only linear combinations of J; the current expression has nonlinear or nonpolynomial J dependence: `1`. Rewrite it as a linear integral combination first.";
dSIBPPublicAPI::derivativefailed = "变量 `1` 的积分导数未能生成。请检查该变量的坐标映射和 seed 闭合。 Integral differentiation with respect to variable `1` could not be generated. Check its coordinate map and seed closure.";


(* ::Chapter:: *)
(*Tree 与 pure-time 消息*)

makeTreeFamilyData::badinput = "tree family 输入无效：`1`。请使用当前 DSInit context 生成的 tree 数据。 Tree-family input is invalid: `1`. Use tree data generated by the current DSInit context.";
treeIntegralShape::badshape = "tree J 的指标长度与当前 family 不一致：`1`。请使用该 context 返回的 master 或 seed 格式。 The index length of tree J is inconsistent with the current family: `1`. Use the master or seed format returned by this context.";
treeDiagonalInverse::singular = "tree 递推需要除以零，当前参数位于奇异层：`1`。请避开这些参数值，或先加入 regulator 再进行递推。 The tree recurrence would divide by zero at the current singular parameter values: `1`. Move away from these values or introduce a regulator before applying the recurrence.";
treeLoopIntegralFromTree::unsupported = "当前 line 状态不能从 tree 表示反投影到 loop seed：`1`。请使用当前支持的 massive-only tree family。 The current line state cannot be back-projected from the tree representation to a loop seed: `1`. Use a currently supported massive-only tree family.";
treeEndpointData::badend = "tree 迭代终点无效：`1`。请给每个活动顶点提供一个整数终点，或使用 Automatic。 The tree-iteration endpoint is invalid: `1`. Supply one integer endpoint per active vertex or use Automatic.";
repIterativeData::badindex = "tree 的时间幂次必须是可判定整数：`1`。请先固定这些指标或加入符号 regulator 后再选择整数移位。 Tree time-power shifts must be decidable integers: `1`. Fix these indices first, or introduce a symbolic regulator before choosing integer shifts.";
repIterativeData::noprogress = "tree 递推不能严格趋近指定终点：`1`。请更换终点，或检查当前参数是否位于奇异层。 The tree recurrence cannot approach the requested endpoint strictly: `1`. Choose another endpoint or check whether the parameters lie on a singular locus.";
repIterativeData::cycle = "tree 递推重复到达同一状态：`1`。计算已停止；请检查终点和奇异参数。 The tree recurrence reached the same state again: `1`. Evaluation stopped; check the endpoint and singular parameters.";
repIterativeData::nosector = "tree 积分无法唯一匹配当前 sector：`1`。请使用 DSInit 返回的 sector-tagged 积分。 The tree integral cannot be matched uniquely to a current sector: `1`. Use a sector-tagged integral returned by DSInit.";
loopToTreeProjection::badloop = "loop-to-tree 投影只接受当前 topology 的合法三槽 loop J：`1`。请使用 DSSeeds 生成的积分。 Loop-to-tree projection accepts only a valid three-slot loop J of the current topology: `1`. Use an integral generated by DSSeeds.";
loopToTreeProjection::mixedcontact = "异分支传播子不能产生 theta/contact 缩并：`1`。请检查 line 的端点顶点类型和 sector。 A mixed-branch propagator cannot produce a theta/contact contraction: `1`. Check the line endpoint vertex types and sector.";
makeTreeTimeReductionRules::incomplete = "tree time seed 的离散态组不完整：`1`。请从同一次 DSTreeSeeds 结果重新生成约化规则。 A discrete-state group of tree time seeds is incomplete: `1`. Regenerate reduction rules from the same DSTreeSeeds result.";
treeFamilyForIntegral::ambiguous = "tree J 的 pack 形状同时匹配多个 sector：`1`。当前表示无法唯一确定 sector，已拒绝继续约化；请使用本次 DSInit 返回的 sector-tagged 积分。 The pack shape of tree J matches multiple sectors: `1`. The current representation cannot determine a unique sector, so reduction was rejected. Use a sector-tagged integral returned by the current DSInit call.";
DSTreeNaiveIBP::badmasters = "DSTreeNaiveIBP 需要非空、无重复且可唯一匹配 sector 的 master 列表。请使用 DSTreeDLogDE 返回的同序 masters，或提供等价列表。 DSTreeNaiveIBP requires a nonempty, duplicate-free master list with unique sector matches. Use the ordered masters returned by DSTreeDLogDE or provide an equivalent list.";
DSTreeNaiveIBP::nonsquare = "tree IBP 方程数 `1` 与待约化对象数 `2` 不相等，无法求解。请检查 seed 完整性和 master 列表。 The tree-IBP equation count `1` differs from the reducible-object count `2`, so the system cannot be solved. Check seed completeness and the master list.";
DSTreeNaiveIBP::solvefailed = "tree IBP 线性系统无法求解。请检查当前参数是否奇异，以及 master 列表是否完整。 The tree-IBP linear system could not be solved. Check for singular parameters and an incomplete master list.";
DSTreeNaiveDE::badibp = "DSTreeNaiveDE 需要 DSTreeNaiveIBP 成功返回的数据或有效 DSInit context。请先完成 tree IBP。 DSTreeNaiveDE requires data returned by a successful DSTreeNaiveIBP call or a valid DSInit context. Complete tree IBP first.";
DSTreeNaiveDE::badvars = "tree 微分变量必须属于当前 family 的外部独立变量：`1`。请从初始化变量列表中选择。 Tree differentiation variables must be independent external variables of the current family: `1`. Choose variables from the initialized list.";
