{<|"caseName" -> "018MixBubbleTreeK1K2", "sectorShrunkLines" -> {}, "sectorKey" -> "top",
  "aSlotMode" -> "compactActiveSlots", "sectorVertexRepresentativeMap" -> <|v1 -> v1, v2 -> v2, v3 -> v3|>,
  "vertexIdToOriginalASlot" -> <|v1 -> 1, v2 -> 2, v3 -> 3|>, "vertexIdToCompactASlot" ->
   <|v1 -> 1, v2 -> 2, v3 -> 3|>, "vertexSlots" -> {<|"slot" -> 1, "vertexId" -> v1, "representativeVertexId" -> v1,
     "aSymbol" -> a[v1], "activeQ" -> True, "fixedValue" -> None, "compactASlot" -> 1|>,
    <|"slot" -> 2, "vertexId" -> v2, "representativeVertexId" -> v2, "aSymbol" -> a[v2], "activeQ" -> True,
     "fixedValue" -> None, "compactASlot" -> 2|>, <|"slot" -> 3, "vertexId" -> v3, "representativeVertexId" -> v3,
     "aSymbol" -> a[v3], "activeQ" -> True, "fixedValue" -> None, "compactASlot" -> 3|>},
  "compactASlots" -> {<|"compactSlot" -> 1, "representativeVertexId" -> v1, "originalVertexIds" -> {v1},
     "originalSlots" -> {1}, "aSymbol" -> a[v1]|>, <|"compactSlot" -> 2, "representativeVertexId" -> v2,
     "originalVertexIds" -> {v2}, "originalSlots" -> {2}, "aSymbol" -> a[v2]|>,
    <|"compactSlot" -> 3, "representativeVertexId" -> v3, "originalVertexIds" -> {v3}, "originalSlots" -> {3},
     "aSymbol" -> a[v3]|>}, "activeASlots" -> {1, 2, 3},
  "lineSlots" -> {<|"slot" -> 1, "lineId" -> 1, "packType" -> "massiveFull", "massType" -> "massive",
     "state" -> "full", "endpoints" -> {v1, v2}, "originalEndpoints" -> {v1, v2},
     "masslessN1ReferenceEndpoint" -> Missing["NotApplicable"], "masslessN1OppositeEndpoint" ->
      Missing["NotApplicable"], "endpointOriginalASlots" -> {1, 2}, "endpointCompactASlots" -> {1, 2},
     "linePowerMode" -> "indexed", "bPosition" -> 1, "bSymbol" -> b[1], "nPositions" -> {2, 3},
     "packTemplate" -> {b[1], n[1, 1], n[1, 2]}, "rootLinePosition" -> 1, "powerSlotKind" -> "cycle",
     "shrunkQ" -> False|>, <|"slot" -> 2, "lineId" -> 2, "packType" -> "masslessFull", "massType" -> "massless",
     "state" -> "full", "endpoints" -> {v1, v2}, "originalEndpoints" -> {v1, v2}, "masslessN1ReferenceEndpoint" -> v1,
     "masslessN1OppositeEndpoint" -> v2, "endpointOriginalASlots" -> {1, 2}, "endpointCompactASlots" -> {1, 2},
     "linePowerMode" -> "indexed", "bPosition" -> 1, "bSymbol" -> b[2], "nPositions" -> {2, 3},
     "packTemplate" -> {b[2], n[2, 1], n[2, 2]}, "rootLinePosition" -> 2, "powerSlotKind" -> "cycle",
     "shrunkQ" -> False|>, <|"slot" -> 3, "lineId" -> 3, "packType" -> "masslessFull", "massType" -> "massless",
     "state" -> "full", "endpoints" -> {v2, v3}, "originalEndpoints" -> {v2, v3}, "masslessN1ReferenceEndpoint" -> v2,
     "masslessN1OppositeEndpoint" -> v3, "endpointOriginalASlots" -> {2, 3}, "endpointCompactASlots" -> {2, 3},
     "linePowerMode" -> "fixedCoefficient", "bPosition" -> Missing["FixedLinePower"], "bSymbol" -> None,
     "nPositions" -> {2, 3}, "packTemplate" -> {"F", n[3, 1], n[3, 2]}, "rootLinePosition" -> 3,
     "powerSlotKind" -> "fixed", "shrunkQ" -> False|>}, "lineIdToSlot" -> <|1 -> 1, 2 -> 2, 3 -> 3|>,
  "bSymbolToLineSlot" -> <|b[1] -> 1, b[2] -> 2|>, "ispSlots" -> {}, "rootLineCount" -> 3,
  "rootLineOrder" -> {1, 2, 3}, "ibpMode" -> "full", "sectorPattern" -> {<|"powerKind" -> "cycle", "state" -> "full"|>,
    <|"powerKind" -> "cycle", "state" -> "full"|>, <|"powerKind" -> "fixed", "state" -> "full"|>},
  "sectorBits" -> Missing["NotTimeOnlyBitString"], "sectorKeySchema" -> <|"type" -> "legacyContractedLineList",
    "storageType" -> "String"|>, "timeOnlyStateSlots" -> {}, "timeOnlyStateCount" -> 0,
  "publicIntegralRepresentation" -> "J[aList,linePacks,ispList]",
  "sectorPrefactorData" -> <|"lineIndices" -> {3}, "parameterKeys" -> {"fixedLine:3"}, "parameterList" -> {ss11},
    "powerList" -> {-beta3}, "powerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3",
       "parameter" -> ss11, "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "full",
       "sourceZeroPoint" -> beta3, "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3,
       "zeroPointOverrideSource" -> "sourceSector", "integerShift" -> 0, "compiledIntegerShift" -> 0,
       "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0, "targetMinusSource" -> 0, "normalizedResidualPower" -> 0,
       "prefactorPower" -> -beta3|>}, "kEIndices" -> {1, 2}, "kEMomenta" -> {k1, k2},
    "kEParameterExpressions" -> {sE1, sE2}, "kEPower" -> kEpower[0, 0],
    "residualPowerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3", "parameter" -> ss11,
       "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "full", "sourceZeroPoint" -> beta3,
       "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3, "zeroPointOverrideSource" -> "sourceSector",
       "integerShift" -> 0, "compiledIntegerShift" -> 0, "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0,
       "targetMinusSource" -> 0, "normalizedResidualPower" -> 0, "prefactorPower" -> -beta3|>},
    "contractionParts" -> {}, "constantPrefactor" -> 1, "normalizationConvention" ->
     "structuralKEPowerAndContact-v1"|>, "builtInRelationData" ->
   {<|"lineIndex" -> 2, "lineId" -> 2, "relations" -> {HoldForm[dSIBP`Private`F[2, 0, 1] + dSIBP`Private`F[2, 1, 0] ==
         0], HoldForm[dSIBP`Private`F[2, 1, 1] + dSIBP`Private`F[2, 0, 0] == 0]}, "canonicalDirection" -> "n2ToZero"|>,
    <|"lineIndex" -> 3, "lineId" -> 3, "relations" -> {HoldForm[dSIBP`Private`F[3, 0, 1] + dSIBP`Private`F[3, 1, 0] ==
         0], HoldForm[dSIBP`Private`F[3, 1, 1] + dSIBP`Private`F[3, 0, 0] == 0]},
     "canonicalDirection" -> "n2ToZero"|>}, "parityData" -> <|"status" -> "disabled",
    "reason" -> "noParityConstraints", "parityUsableQ" -> True, "constraints" -> {}|>,
  "representation" -> "J[aList,linePacks,ispList]"|>, <|"caseName" -> "018MixBubbleTreeK1K2_sector_e1",
  "sectorShrunkLines" -> {1}, "sectorKey" -> "e1", "aSlotMode" -> "compactActiveSlots",
  "sectorVertexRepresentativeMap" -> <|v1 -> v1, v2 -> v1, v3 -> v3|>,
  "vertexIdToOriginalASlot" -> <|v1 -> 1, v2 -> 2, v3 -> 3|>, "vertexIdToCompactASlot" ->
   <|v1 -> 1, v2 -> 1, v3 -> 2|>, "vertexSlots" -> {<|"slot" -> 1, "vertexId" -> v1, "representativeVertexId" -> v1,
     "aSymbol" -> a[v1], "activeQ" -> True, "fixedValue" -> None, "compactASlot" -> 1|>,
    <|"slot" -> 2, "vertexId" -> v2, "representativeVertexId" -> v1, "aSymbol" -> a[v2], "activeQ" -> False,
     "fixedValue" -> 0, "compactASlot" -> 1|>, <|"slot" -> 3, "vertexId" -> v3, "representativeVertexId" -> v3,
     "aSymbol" -> a[v3], "activeQ" -> True, "fixedValue" -> None, "compactASlot" -> 2|>},
  "compactASlots" -> {<|"compactSlot" -> 1, "representativeVertexId" -> v1, "originalVertexIds" -> {v1, v2},
     "originalSlots" -> {1, 2}, "aSymbol" -> a[v1]|>, <|"compactSlot" -> 2, "representativeVertexId" -> v3,
     "originalVertexIds" -> {v3}, "originalSlots" -> {3}, "aSymbol" -> a[v3]|>}, "activeASlots" -> {1, 2},
  "lineSlots" -> {<|"slot" -> 1, "lineId" -> 1, "packType" -> "shrunk", "massType" -> "massive", "state" -> "shrunk",
     "endpoints" -> {v1, v1}, "originalEndpoints" -> {v1, v2}, "masslessN1ReferenceEndpoint" ->
      Missing["NotApplicable"], "masslessN1OppositeEndpoint" -> Missing["NotApplicable"],
     "endpointOriginalASlots" -> {1, 2}, "endpointCompactASlots" -> {1, 1}, "linePowerMode" -> "indexed",
     "bPosition" -> 1, "bSymbol" -> bS[1], "nPositions" -> {}, "packTemplate" -> {bS[1]}, "rootLinePosition" -> 1,
     "powerSlotKind" -> "cycle", "shrunkQ" -> True|>, <|"slot" -> 2, "lineId" -> 2, "packType" -> "masslessFull",
     "massType" -> "massless", "state" -> "full", "endpoints" -> {v1, v1}, "originalEndpoints" -> {v1, v2},
     "masslessN1ReferenceEndpoint" -> v1, "masslessN1OppositeEndpoint" -> v2, "endpointOriginalASlots" -> {1, 2},
     "endpointCompactASlots" -> {1, 1}, "linePowerMode" -> "indexed", "bPosition" -> 1, "bSymbol" -> b[2],
     "nPositions" -> {2, 3}, "packTemplate" -> {b[2], n[2, 1], n[2, 2]}, "rootLinePosition" -> 2,
     "powerSlotKind" -> "cycle", "shrunkQ" -> False|>, <|"slot" -> 3, "lineId" -> 3, "packType" -> "masslessFull",
     "massType" -> "massless", "state" -> "full", "endpoints" -> {v1, v3}, "originalEndpoints" -> {v2, v3},
     "masslessN1ReferenceEndpoint" -> v2, "masslessN1OppositeEndpoint" -> v3, "endpointOriginalASlots" -> {2, 3},
     "endpointCompactASlots" -> {1, 2}, "linePowerMode" -> "fixedCoefficient",
     "bPosition" -> Missing["FixedLinePower"], "bSymbol" -> None, "nPositions" -> {2, 3},
     "packTemplate" -> {"F", n[3, 1], n[3, 2]}, "rootLinePosition" -> 3, "powerSlotKind" -> "fixed",
     "shrunkQ" -> False|>}, "lineIdToSlot" -> <|1 -> 1, 2 -> 2, 3 -> 3|>,
  "bSymbolToLineSlot" -> <|bS[1] -> 1, b[2] -> 2|>, "ispSlots" -> {}, "rootLineCount" -> 3,
  "rootLineOrder" -> {1, 2, 3}, "ibpMode" -> "full", "sectorPattern" ->
   {<|"powerKind" -> "cycle", "state" -> "shrunk"|>, <|"powerKind" -> "cycle", "state" -> "full"|>,
    <|"powerKind" -> "fixed", "state" -> "full"|>}, "sectorBits" -> Missing["NotTimeOnlyBitString"],
  "sectorKeySchema" -> <|"type" -> "legacyContractedLineList", "storageType" -> "String"|>, "timeOnlyStateSlots" -> {},
  "timeOnlyStateCount" -> 0, "publicIntegralRepresentation" -> "J[aList,linePacks,ispList]",
  "sectorPrefactorData" -> <|"lineIndices" -> {3}, "parameterKeys" -> {"fixedLine:3"}, "parameterList" -> {ss11},
    "powerList" -> {-beta3}, "powerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3",
       "parameter" -> ss11, "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "full",
       "sourceZeroPoint" -> beta3, "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3,
       "zeroPointOverrideSource" -> "sourceSector", "integerShift" -> 0, "compiledIntegerShift" -> 0,
       "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0, "targetMinusSource" -> 0, "normalizedResidualPower" -> 0,
       "prefactorPower" -> -beta3|>}, "kEIndices" -> {1, 2}, "kEMomenta" -> {k1, k2},
    "kEParameterExpressions" -> {sE1, sE2}, "kEPower" -> kEpower[0, 0],
    "residualPowerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3", "parameter" -> ss11,
       "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "full", "sourceZeroPoint" -> beta3,
       "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3, "zeroPointOverrideSource" -> "sourceSector",
       "integerShift" -> 0, "compiledIntegerShift" -> 0, "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0,
       "targetMinusSource" -> 0, "normalizedResidualPower" -> 0, "prefactorPower" -> -beta3|>},
    "contractionParts" -> {<|"lineIndex" -> 1, "lineId" -> 1, "normalizationFactor" -> ((4*I)*E^(Pi*Im[nu1]))/Pi|>},
    "constantPrefactor" -> ((4*I)*E^(Pi*Im[nu1]))/Pi, "normalizationConvention" -> "structuralKEPowerAndContact-v1"|>,
  "builtInRelationData" -> {<|"lineIndex" -> 2, "lineId" -> 2,
     "relations" -> {HoldForm[dSIBP`Private`F[2, 0, 1] + dSIBP`Private`F[2, 1, 0] == 0],
       HoldForm[dSIBP`Private`F[2, 1, 1] + dSIBP`Private`F[2, 0, 0] == 0]}, "canonicalDirection" -> "n2ToZero"|>,
    <|"lineIndex" -> 3, "lineId" -> 3, "relations" -> {HoldForm[dSIBP`Private`F[3, 0, 1] + dSIBP`Private`F[3, 1, 0] ==
         0], HoldForm[dSIBP`Private`F[3, 1, 1] + dSIBP`Private`F[3, 0, 0] == 0]},
     "canonicalDirection" -> "n2ToZero"|>}, "parityData" -> <|"status" -> "disabled",
    "reason" -> "noParityConstraints", "parityUsableQ" -> True, "constraints" -> {}|>,
  "representation" -> "J[aList,linePacks,ispList]"|>, <|"caseName" -> "018MixBubbleTreeK1K2_sector_e2",
  "sectorShrunkLines" -> {2}, "sectorKey" -> "e2", "aSlotMode" -> "compactActiveSlots",
  "sectorVertexRepresentativeMap" -> <|v1 -> v1, v2 -> v1, v3 -> v3|>,
  "vertexIdToOriginalASlot" -> <|v1 -> 1, v2 -> 2, v3 -> 3|>, "vertexIdToCompactASlot" ->
   <|v1 -> 1, v2 -> 1, v3 -> 2|>, "vertexSlots" -> {<|"slot" -> 1, "vertexId" -> v1, "representativeVertexId" -> v1,
     "aSymbol" -> a[v1], "activeQ" -> True, "fixedValue" -> None, "compactASlot" -> 1|>,
    <|"slot" -> 2, "vertexId" -> v2, "representativeVertexId" -> v1, "aSymbol" -> a[v2], "activeQ" -> False,
     "fixedValue" -> 0, "compactASlot" -> 1|>, <|"slot" -> 3, "vertexId" -> v3, "representativeVertexId" -> v3,
     "aSymbol" -> a[v3], "activeQ" -> True, "fixedValue" -> None, "compactASlot" -> 2|>},
  "compactASlots" -> {<|"compactSlot" -> 1, "representativeVertexId" -> v1, "originalVertexIds" -> {v1, v2},
     "originalSlots" -> {1, 2}, "aSymbol" -> a[v1]|>, <|"compactSlot" -> 2, "representativeVertexId" -> v3,
     "originalVertexIds" -> {v3}, "originalSlots" -> {3}, "aSymbol" -> a[v3]|>}, "activeASlots" -> {1, 2},
  "lineSlots" -> {<|"slot" -> 1, "lineId" -> 1, "packType" -> "massiveFull", "massType" -> "massive",
     "state" -> "full", "endpoints" -> {v1, v1}, "originalEndpoints" -> {v1, v2},
     "masslessN1ReferenceEndpoint" -> Missing["NotApplicable"], "masslessN1OppositeEndpoint" ->
      Missing["NotApplicable"], "endpointOriginalASlots" -> {1, 2}, "endpointCompactASlots" -> {1, 1},
     "linePowerMode" -> "indexed", "bPosition" -> 1, "bSymbol" -> b[1], "nPositions" -> {2, 3},
     "packTemplate" -> {b[1], n[1, 1], n[1, 2]}, "rootLinePosition" -> 1, "powerSlotKind" -> "cycle",
     "shrunkQ" -> False|>, <|"slot" -> 2, "lineId" -> 2, "packType" -> "shrunk", "massType" -> "massless",
     "state" -> "shrunk", "endpoints" -> {v1, v1}, "originalEndpoints" -> {v1, v2},
     "masslessN1ReferenceEndpoint" -> Missing["NotApplicable"], "masslessN1OppositeEndpoint" ->
      Missing["NotApplicable"], "endpointOriginalASlots" -> {1, 2}, "endpointCompactASlots" -> {1, 1},
     "linePowerMode" -> "indexed", "bPosition" -> 1, "bSymbol" -> bS[2], "nPositions" -> {}, "packTemplate" -> {bS[2]},
     "rootLinePosition" -> 2, "powerSlotKind" -> "cycle", "shrunkQ" -> True|>,
    <|"slot" -> 3, "lineId" -> 3, "packType" -> "masslessFull", "massType" -> "massless", "state" -> "full",
     "endpoints" -> {v1, v3}, "originalEndpoints" -> {v2, v3}, "masslessN1ReferenceEndpoint" -> v2,
     "masslessN1OppositeEndpoint" -> v3, "endpointOriginalASlots" -> {2, 3}, "endpointCompactASlots" -> {1, 2},
     "linePowerMode" -> "fixedCoefficient", "bPosition" -> Missing["FixedLinePower"], "bSymbol" -> None,
     "nPositions" -> {2, 3}, "packTemplate" -> {"F", n[3, 1], n[3, 2]}, "rootLinePosition" -> 3,
     "powerSlotKind" -> "fixed", "shrunkQ" -> False|>}, "lineIdToSlot" -> <|1 -> 1, 2 -> 2, 3 -> 3|>,
  "bSymbolToLineSlot" -> <|b[1] -> 1, bS[2] -> 2|>, "ispSlots" -> {}, "rootLineCount" -> 3,
  "rootLineOrder" -> {1, 2, 3}, "ibpMode" -> "full", "sectorPattern" -> {<|"powerKind" -> "cycle", "state" -> "full"|>,
    <|"powerKind" -> "cycle", "state" -> "shrunk"|>, <|"powerKind" -> "fixed", "state" -> "full"|>},
  "sectorBits" -> Missing["NotTimeOnlyBitString"], "sectorKeySchema" -> <|"type" -> "legacyContractedLineList",
    "storageType" -> "String"|>, "timeOnlyStateSlots" -> {}, "timeOnlyStateCount" -> 0,
  "publicIntegralRepresentation" -> "J[aList,linePacks,ispList]",
  "sectorPrefactorData" -> <|"lineIndices" -> {3}, "parameterKeys" -> {"fixedLine:3"}, "parameterList" -> {ss11},
    "powerList" -> {-beta3}, "powerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3",
       "parameter" -> ss11, "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "full",
       "sourceZeroPoint" -> beta3, "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3,
       "zeroPointOverrideSource" -> "sourceSector", "integerShift" -> 0, "compiledIntegerShift" -> 0,
       "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0, "targetMinusSource" -> 0, "normalizedResidualPower" -> 0,
       "prefactorPower" -> -beta3|>}, "kEIndices" -> {1, 2}, "kEMomenta" -> {k1, k2},
    "kEParameterExpressions" -> {sE1, sE2}, "kEPower" -> kEpower[0, 0],
    "residualPowerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3", "parameter" -> ss11,
       "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "full", "sourceZeroPoint" -> beta3,
       "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3, "zeroPointOverrideSource" -> "sourceSector",
       "integerShift" -> 0, "compiledIntegerShift" -> 0, "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0,
       "targetMinusSource" -> 0, "normalizedResidualPower" -> 0, "prefactorPower" -> -beta3|>},
    "contractionParts" -> {<|"lineIndex" -> 2, "lineId" -> 2, "normalizationFactor" -> 1|>}, "constantPrefactor" -> 1,
    "normalizationConvention" -> "structuralKEPowerAndContact-v1"|>,
  "builtInRelationData" -> {<|"lineIndex" -> 3, "lineId" -> 3,
     "relations" -> {HoldForm[dSIBP`Private`F[3, 0, 1] + dSIBP`Private`F[3, 1, 0] == 0],
       HoldForm[dSIBP`Private`F[3, 1, 1] + dSIBP`Private`F[3, 0, 0] == 0]}, "canonicalDirection" -> "n2ToZero"|>},
  "parityData" -> <|"status" -> "disabled", "reason" -> "noParityConstraints", "parityUsableQ" -> True,
    "constraints" -> {}|>, "representation" -> "J[aList,linePacks,ispList]"|>,
 <|"caseName" -> "018MixBubbleTreeK1K2_sector_e3", "sectorShrunkLines" -> {3}, "sectorKey" -> "e3",
  "aSlotMode" -> "compactActiveSlots", "sectorVertexRepresentativeMap" -> <|v1 -> v1, v2 -> v2, v3 -> v2|>,
  "vertexIdToOriginalASlot" -> <|v1 -> 1, v2 -> 2, v3 -> 3|>, "vertexIdToCompactASlot" ->
   <|v1 -> 1, v2 -> 2, v3 -> 2|>, "vertexSlots" -> {<|"slot" -> 1, "vertexId" -> v1, "representativeVertexId" -> v1,
     "aSymbol" -> a[v1], "activeQ" -> True, "fixedValue" -> None, "compactASlot" -> 1|>,
    <|"slot" -> 2, "vertexId" -> v2, "representativeVertexId" -> v2, "aSymbol" -> a[v2], "activeQ" -> True,
     "fixedValue" -> None, "compactASlot" -> 2|>, <|"slot" -> 3, "vertexId" -> v3, "representativeVertexId" -> v2,
     "aSymbol" -> a[v3], "activeQ" -> False, "fixedValue" -> 0, "compactASlot" -> 2|>},
  "compactASlots" -> {<|"compactSlot" -> 1, "representativeVertexId" -> v1, "originalVertexIds" -> {v1},
     "originalSlots" -> {1}, "aSymbol" -> a[v1]|>, <|"compactSlot" -> 2, "representativeVertexId" -> v2,
     "originalVertexIds" -> {v2, v3}, "originalSlots" -> {2, 3}, "aSymbol" -> a[v2]|>}, "activeASlots" -> {1, 2},
  "lineSlots" -> {<|"slot" -> 1, "lineId" -> 1, "packType" -> "massiveFull", "massType" -> "massive",
     "state" -> "full", "endpoints" -> {v1, v2}, "originalEndpoints" -> {v1, v2},
     "masslessN1ReferenceEndpoint" -> Missing["NotApplicable"], "masslessN1OppositeEndpoint" ->
      Missing["NotApplicable"], "endpointOriginalASlots" -> {1, 2}, "endpointCompactASlots" -> {1, 2},
     "linePowerMode" -> "indexed", "bPosition" -> 1, "bSymbol" -> b[1], "nPositions" -> {2, 3},
     "packTemplate" -> {b[1], n[1, 1], n[1, 2]}, "rootLinePosition" -> 1, "powerSlotKind" -> "cycle",
     "shrunkQ" -> False|>, <|"slot" -> 2, "lineId" -> 2, "packType" -> "masslessFull", "massType" -> "massless",
     "state" -> "full", "endpoints" -> {v1, v2}, "originalEndpoints" -> {v1, v2}, "masslessN1ReferenceEndpoint" -> v1,
     "masslessN1OppositeEndpoint" -> v2, "endpointOriginalASlots" -> {1, 2}, "endpointCompactASlots" -> {1, 2},
     "linePowerMode" -> "indexed", "bPosition" -> 1, "bSymbol" -> b[2], "nPositions" -> {2, 3},
     "packTemplate" -> {b[2], n[2, 1], n[2, 2]}, "rootLinePosition" -> 2, "powerSlotKind" -> "cycle",
     "shrunkQ" -> False|>, <|"slot" -> 3, "lineId" -> 3, "packType" -> "shrunk", "massType" -> "massless",
     "state" -> "shrunk", "endpoints" -> {v2, v2}, "originalEndpoints" -> {v2, v3},
     "masslessN1ReferenceEndpoint" -> Missing["NotApplicable"], "masslessN1OppositeEndpoint" ->
      Missing["NotApplicable"], "endpointOriginalASlots" -> {2, 3}, "endpointCompactASlots" -> {2, 2},
     "linePowerMode" -> "fixedCoefficient", "bPosition" -> Missing["FixedLinePower"], "bSymbol" -> None,
     "nPositions" -> {}, "packTemplate" -> {"F"}, "rootLinePosition" -> 3, "powerSlotKind" -> "fixed",
     "shrunkQ" -> True|>}, "lineIdToSlot" -> <|1 -> 1, 2 -> 2, 3 -> 3|>,
  "bSymbolToLineSlot" -> <|b[1] -> 1, b[2] -> 2|>, "ispSlots" -> {}, "rootLineCount" -> 3,
  "rootLineOrder" -> {1, 2, 3}, "ibpMode" -> "full", "sectorPattern" -> {<|"powerKind" -> "cycle", "state" -> "full"|>,
    <|"powerKind" -> "cycle", "state" -> "full"|>, <|"powerKind" -> "fixed", "state" -> "shrunk"|>},
  "sectorBits" -> Missing["NotTimeOnlyBitString"], "sectorKeySchema" -> <|"type" -> "legacyContractedLineList",
    "storageType" -> "String"|>, "timeOnlyStateSlots" -> {}, "timeOnlyStateCount" -> 0,
  "publicIntegralRepresentation" -> "J[aList,linePacks,ispList]",
  "sectorPrefactorData" -> <|"lineIndices" -> {3}, "parameterKeys" -> {"fixedLine:3"}, "parameterList" -> {ss11},
    "powerList" -> {-beta3}, "powerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3",
       "parameter" -> ss11, "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "shrunk",
       "sourceZeroPoint" -> beta3, "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3,
       "zeroPointOverrideSource" -> "compiledDefault", "integerShift" -> 0, "compiledIntegerShift" -> 0,
       "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0, "targetMinusSource" -> 0, "normalizedResidualPower" -> 0,
       "prefactorPower" -> -beta3|>}, "kEIndices" -> {1, 2}, "kEMomenta" -> {k1, k2},
    "kEParameterExpressions" -> {sE1, sE2}, "kEPower" -> kEpower[0, 0],
    "residualPowerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3", "parameter" -> ss11,
       "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "shrunk", "sourceZeroPoint" -> beta3,
       "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3, "zeroPointOverrideSource" -> "compiledDefault",
       "integerShift" -> 0, "compiledIntegerShift" -> 0, "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0,
       "targetMinusSource" -> 0, "normalizedResidualPower" -> 0, "prefactorPower" -> -beta3|>},
    "contractionParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "normalizationFactor" -> 1|>}, "constantPrefactor" -> 1,
    "normalizationConvention" -> "structuralKEPowerAndContact-v1"|>,
  "builtInRelationData" -> {<|"lineIndex" -> 2, "lineId" -> 2,
     "relations" -> {HoldForm[dSIBP`Private`F[2, 0, 1] + dSIBP`Private`F[2, 1, 0] == 0],
       HoldForm[dSIBP`Private`F[2, 1, 1] + dSIBP`Private`F[2, 0, 0] == 0]}, "canonicalDirection" -> "n2ToZero"|>},
  "parityData" -> <|"status" -> "disabled", "reason" -> "noParityConstraints", "parityUsableQ" -> True,
    "constraints" -> {}|>, "representation" -> "J[aList,linePacks,ispList]"|>,
 <|"caseName" -> "018MixBubbleTreeK1K2_sector_e1_e3", "sectorShrunkLines" -> {1, 3}, "sectorKey" -> "e1_e3",
  "aSlotMode" -> "compactActiveSlots", "sectorVertexRepresentativeMap" -> <|v1 -> v1, v2 -> v1, v3 -> v1|>,
  "vertexIdToOriginalASlot" -> <|v1 -> 1, v2 -> 2, v3 -> 3|>, "vertexIdToCompactASlot" ->
   <|v1 -> 1, v2 -> 1, v3 -> 1|>, "vertexSlots" -> {<|"slot" -> 1, "vertexId" -> v1, "representativeVertexId" -> v1,
     "aSymbol" -> a[v1], "activeQ" -> True, "fixedValue" -> None, "compactASlot" -> 1|>,
    <|"slot" -> 2, "vertexId" -> v2, "representativeVertexId" -> v1, "aSymbol" -> a[v2], "activeQ" -> False,
     "fixedValue" -> 0, "compactASlot" -> 1|>, <|"slot" -> 3, "vertexId" -> v3, "representativeVertexId" -> v1,
     "aSymbol" -> a[v3], "activeQ" -> False, "fixedValue" -> 0, "compactASlot" -> 1|>},
  "compactASlots" -> {<|"compactSlot" -> 1, "representativeVertexId" -> v1, "originalVertexIds" -> {v1, v2, v3},
     "originalSlots" -> {1, 2, 3}, "aSymbol" -> a[v1]|>}, "activeASlots" -> {1},
  "lineSlots" -> {<|"slot" -> 1, "lineId" -> 1, "packType" -> "shrunk", "massType" -> "massive", "state" -> "shrunk",
     "endpoints" -> {v1, v1}, "originalEndpoints" -> {v1, v2}, "masslessN1ReferenceEndpoint" ->
      Missing["NotApplicable"], "masslessN1OppositeEndpoint" -> Missing["NotApplicable"],
     "endpointOriginalASlots" -> {1, 2}, "endpointCompactASlots" -> {1, 1}, "linePowerMode" -> "indexed",
     "bPosition" -> 1, "bSymbol" -> bS[1], "nPositions" -> {}, "packTemplate" -> {bS[1]}, "rootLinePosition" -> 1,
     "powerSlotKind" -> "cycle", "shrunkQ" -> True|>, <|"slot" -> 2, "lineId" -> 2, "packType" -> "masslessFull",
     "massType" -> "massless", "state" -> "full", "endpoints" -> {v1, v1}, "originalEndpoints" -> {v1, v2},
     "masslessN1ReferenceEndpoint" -> v1, "masslessN1OppositeEndpoint" -> v2, "endpointOriginalASlots" -> {1, 2},
     "endpointCompactASlots" -> {1, 1}, "linePowerMode" -> "indexed", "bPosition" -> 1, "bSymbol" -> b[2],
     "nPositions" -> {2, 3}, "packTemplate" -> {b[2], n[2, 1], n[2, 2]}, "rootLinePosition" -> 2,
     "powerSlotKind" -> "cycle", "shrunkQ" -> False|>, <|"slot" -> 3, "lineId" -> 3, "packType" -> "shrunk",
     "massType" -> "massless", "state" -> "shrunk", "endpoints" -> {v1, v1}, "originalEndpoints" -> {v2, v3},
     "masslessN1ReferenceEndpoint" -> Missing["NotApplicable"], "masslessN1OppositeEndpoint" ->
      Missing["NotApplicable"], "endpointOriginalASlots" -> {2, 3}, "endpointCompactASlots" -> {1, 1},
     "linePowerMode" -> "fixedCoefficient", "bPosition" -> Missing["FixedLinePower"], "bSymbol" -> None,
     "nPositions" -> {}, "packTemplate" -> {"F"}, "rootLinePosition" -> 3, "powerSlotKind" -> "fixed",
     "shrunkQ" -> True|>}, "lineIdToSlot" -> <|1 -> 1, 2 -> 2, 3 -> 3|>,
  "bSymbolToLineSlot" -> <|bS[1] -> 1, b[2] -> 2|>, "ispSlots" -> {}, "rootLineCount" -> 3,
  "rootLineOrder" -> {1, 2, 3}, "ibpMode" -> "full", "sectorPattern" ->
   {<|"powerKind" -> "cycle", "state" -> "shrunk"|>, <|"powerKind" -> "cycle", "state" -> "full"|>,
    <|"powerKind" -> "fixed", "state" -> "shrunk"|>}, "sectorBits" -> Missing["NotTimeOnlyBitString"],
  "sectorKeySchema" -> <|"type" -> "legacyContractedLineList", "storageType" -> "String"|>, "timeOnlyStateSlots" -> {},
  "timeOnlyStateCount" -> 0, "publicIntegralRepresentation" -> "J[aList,linePacks,ispList]",
  "sectorPrefactorData" -> <|"lineIndices" -> {3}, "parameterKeys" -> {"fixedLine:3"}, "parameterList" -> {ss11},
    "powerList" -> {-beta3}, "powerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3",
       "parameter" -> ss11, "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "shrunk",
       "sourceZeroPoint" -> beta3, "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3,
       "zeroPointOverrideSource" -> "compiledDefault", "integerShift" -> 0, "compiledIntegerShift" -> 0,
       "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0, "targetMinusSource" -> 0, "normalizedResidualPower" -> 0,
       "prefactorPower" -> -beta3|>}, "kEIndices" -> {1, 2}, "kEMomenta" -> {k1, k2},
    "kEParameterExpressions" -> {sE1, sE2}, "kEPower" -> kEpower[0, 0],
    "residualPowerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3", "parameter" -> ss11,
       "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "shrunk", "sourceZeroPoint" -> beta3,
       "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3, "zeroPointOverrideSource" -> "compiledDefault",
       "integerShift" -> 0, "compiledIntegerShift" -> 0, "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0,
       "targetMinusSource" -> 0, "normalizedResidualPower" -> 0, "prefactorPower" -> -beta3|>},
    "contractionParts" -> {<|"lineIndex" -> 1, "lineId" -> 1, "normalizationFactor" -> ((4*I)*E^(Pi*Im[nu1]))/Pi|>,
      <|"lineIndex" -> 3, "lineId" -> 3, "normalizationFactor" -> 1|>},
    "constantPrefactor" -> ((4*I)*E^(Pi*Im[nu1]))/Pi, "normalizationConvention" -> "structuralKEPowerAndContact-v1"|>,
  "builtInRelationData" -> {<|"lineIndex" -> 2, "lineId" -> 2,
     "relations" -> {HoldForm[dSIBP`Private`F[2, 0, 1] + dSIBP`Private`F[2, 1, 0] == 0],
       HoldForm[dSIBP`Private`F[2, 1, 1] + dSIBP`Private`F[2, 0, 0] == 0]}, "canonicalDirection" -> "n2ToZero"|>},
  "parityData" -> <|"status" -> "disabled", "reason" -> "noParityConstraints", "parityUsableQ" -> True,
    "constraints" -> {}|>, "representation" -> "J[aList,linePacks,ispList]"|>,
 <|"caseName" -> "018MixBubbleTreeK1K2_sector_e2_e3", "sectorShrunkLines" -> {2, 3}, "sectorKey" -> "e2_e3",
  "aSlotMode" -> "compactActiveSlots", "sectorVertexRepresentativeMap" -> <|v1 -> v1, v2 -> v1, v3 -> v1|>,
  "vertexIdToOriginalASlot" -> <|v1 -> 1, v2 -> 2, v3 -> 3|>, "vertexIdToCompactASlot" ->
   <|v1 -> 1, v2 -> 1, v3 -> 1|>, "vertexSlots" -> {<|"slot" -> 1, "vertexId" -> v1, "representativeVertexId" -> v1,
     "aSymbol" -> a[v1], "activeQ" -> True, "fixedValue" -> None, "compactASlot" -> 1|>,
    <|"slot" -> 2, "vertexId" -> v2, "representativeVertexId" -> v1, "aSymbol" -> a[v2], "activeQ" -> False,
     "fixedValue" -> 0, "compactASlot" -> 1|>, <|"slot" -> 3, "vertexId" -> v3, "representativeVertexId" -> v1,
     "aSymbol" -> a[v3], "activeQ" -> False, "fixedValue" -> 0, "compactASlot" -> 1|>},
  "compactASlots" -> {<|"compactSlot" -> 1, "representativeVertexId" -> v1, "originalVertexIds" -> {v1, v2, v3},
     "originalSlots" -> {1, 2, 3}, "aSymbol" -> a[v1]|>}, "activeASlots" -> {1},
  "lineSlots" -> {<|"slot" -> 1, "lineId" -> 1, "packType" -> "massiveFull", "massType" -> "massive",
     "state" -> "full", "endpoints" -> {v1, v1}, "originalEndpoints" -> {v1, v2},
     "masslessN1ReferenceEndpoint" -> Missing["NotApplicable"], "masslessN1OppositeEndpoint" ->
      Missing["NotApplicable"], "endpointOriginalASlots" -> {1, 2}, "endpointCompactASlots" -> {1, 1},
     "linePowerMode" -> "indexed", "bPosition" -> 1, "bSymbol" -> b[1], "nPositions" -> {2, 3},
     "packTemplate" -> {b[1], n[1, 1], n[1, 2]}, "rootLinePosition" -> 1, "powerSlotKind" -> "cycle",
     "shrunkQ" -> False|>, <|"slot" -> 2, "lineId" -> 2, "packType" -> "shrunk", "massType" -> "massless",
     "state" -> "shrunk", "endpoints" -> {v1, v1}, "originalEndpoints" -> {v1, v2},
     "masslessN1ReferenceEndpoint" -> Missing["NotApplicable"], "masslessN1OppositeEndpoint" ->
      Missing["NotApplicable"], "endpointOriginalASlots" -> {1, 2}, "endpointCompactASlots" -> {1, 1},
     "linePowerMode" -> "indexed", "bPosition" -> 1, "bSymbol" -> bS[2], "nPositions" -> {}, "packTemplate" -> {bS[2]},
     "rootLinePosition" -> 2, "powerSlotKind" -> "cycle", "shrunkQ" -> True|>,
    <|"slot" -> 3, "lineId" -> 3, "packType" -> "shrunk", "massType" -> "massless", "state" -> "shrunk",
     "endpoints" -> {v1, v1}, "originalEndpoints" -> {v2, v3}, "masslessN1ReferenceEndpoint" ->
      Missing["NotApplicable"], "masslessN1OppositeEndpoint" -> Missing["NotApplicable"],
     "endpointOriginalASlots" -> {2, 3}, "endpointCompactASlots" -> {1, 1}, "linePowerMode" -> "fixedCoefficient",
     "bPosition" -> Missing["FixedLinePower"], "bSymbol" -> None, "nPositions" -> {}, "packTemplate" -> {"F"},
     "rootLinePosition" -> 3, "powerSlotKind" -> "fixed", "shrunkQ" -> True|>},
  "lineIdToSlot" -> <|1 -> 1, 2 -> 2, 3 -> 3|>, "bSymbolToLineSlot" -> <|b[1] -> 1, bS[2] -> 2|>, "ispSlots" -> {},
  "rootLineCount" -> 3, "rootLineOrder" -> {1, 2, 3}, "ibpMode" -> "full",
  "sectorPattern" -> {<|"powerKind" -> "cycle", "state" -> "full"|>, <|"powerKind" -> "cycle", "state" -> "shrunk"|>,
    <|"powerKind" -> "fixed", "state" -> "shrunk"|>}, "sectorBits" -> Missing["NotTimeOnlyBitString"],
  "sectorKeySchema" -> <|"type" -> "legacyContractedLineList", "storageType" -> "String"|>, "timeOnlyStateSlots" -> {},
  "timeOnlyStateCount" -> 0, "publicIntegralRepresentation" -> "J[aList,linePacks,ispList]",
  "sectorPrefactorData" -> <|"lineIndices" -> {3}, "parameterKeys" -> {"fixedLine:3"}, "parameterList" -> {ss11},
    "powerList" -> {-beta3}, "powerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3",
       "parameter" -> ss11, "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "shrunk",
       "sourceZeroPoint" -> beta3, "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3,
       "zeroPointOverrideSource" -> "compiledDefault", "integerShift" -> 0, "compiledIntegerShift" -> 0,
       "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0, "targetMinusSource" -> 0, "normalizedResidualPower" -> 0,
       "prefactorPower" -> -beta3|>}, "kEIndices" -> {1, 2}, "kEMomenta" -> {k1, k2},
    "kEParameterExpressions" -> {sE1, sE2}, "kEPower" -> kEpower[0, 0],
    "residualPowerParts" -> {<|"lineIndex" -> 3, "lineId" -> 3, "parameterKey" -> "fixedLine:3", "parameter" -> ss11,
       "kEIndex" -> Missing["NotIndependentExternalMagnitude"], "state" -> "shrunk", "sourceZeroPoint" -> beta3,
       "targetZeroPoint" -> beta3, "derivedTargetZeroPoint" -> beta3, "zeroPointOverrideSource" -> "compiledDefault",
       "integerShift" -> 0, "compiledIntegerShift" -> 0, "zeroPointShift" -> 0, "compiledZeroPointShift" -> 0,
       "targetMinusSource" -> 0, "normalizedResidualPower" -> 0, "prefactorPower" -> -beta3|>},
    "contractionParts" -> {<|"lineIndex" -> 2, "lineId" -> 2, "normalizationFactor" -> 1|>,
      <|"lineIndex" -> 3, "lineId" -> 3, "normalizationFactor" -> 1|>}, "constantPrefactor" -> 1,
    "normalizationConvention" -> "structuralKEPowerAndContact-v1"|>, "builtInRelationData" -> {},
  "parityData" -> <|"status" -> "disabled", "reason" -> "noParityConstraints", "parityUsableQ" -> True,
    "constraints" -> {}|>, "representation" -> "J[aList,linePacks,ispList]"|>}
