(* ::Package:: *)

(* 本文件实现 016 的模板化连续指标撒点。DSSeeds 先生成完整离散态并执行
   EOM/canonical；本模块只展开 general 连续指标，并保留可供 DSLinear 审计的来源信息。 *)


(* ::Chapter:: *)
(*Seed 模板构造与完整性封装*)

If[! ValueQ[$dSIBPLastSeedTemplates], $dSIBPLastSeedTemplates = Missing["NotGenerated"]];


DSAllSeeds::noseeds = "尚未生成 seed 模板。请先成功调用 DSSeeds。 No seed templates are available. Run DSSeeds successfully first.";
DSAllSeeds::badseed = "输入不含 DSSeeds 生成的 allSeeds。 The input does not contain allSeeds generated by DSSeeds.";


dsTemplateSource[sectorKey_String, ibpClass_String, shrunkLines_List] := Which[
   sectorKey === "top" && ibpClass === "qIBP", "momentum",
   sectorKey === "top" && ibpClass === "tIBP", "time",
   ibpClass === "qIBP", {"shrinkSectorMomentum", shrunkLines},
   True, {"shrinkSectorTime", shrunkLines}
   ];


dsTemplateGeneratorLabel[generator_Association] := If[
   Lookup[generator, "type", "missing"] === "time",
   timeGeneratorLabel[generator],
   momentumGeneratorLabel[generator]
   ];


dsTemplateGeneratorClass[generator_Association] := If[
   Lookup[generator, "type", "missing"] === "time", "tIBP", "qIBP"
   ];


(* loop 模板只遍历离散 n=0,1，不代入任何连续指标。这样 EOM 在撒点前完成，
   而 a/b/ISP 仍能由 DSGenerateIBP 统一或逐指标展开。 *)
dsLoopTemplatesForTopology[topo_Association] := Module[
   {base, continuousIndices, discreteVariables, discreteData, generators, rawTemplates,
    sectorKey, shrunkLines, metadata, representation, records},
   base = makeBaseIntegral[topo];
   continuousIndices = continuousIndexVariables[base];
   discreteVariables = DeleteDuplicates[Cases[base, _n, Infinity]];
   discreteData = selectedDiscreteSeedRules[topo];
   If[Lookup[discreteData, "status", "failed"] =!= "generated",
    Return[<|"status" -> "failed", "reason" -> "discreteEnumerationFailed",
      "sectorKey" -> sectorKeyFromShrunkLines[Lookup[topo, "sectorShrunkLines", {}]],
      "discreteData" -> discreteData|>]
    ];
   generators = Select[
     makeIBPGenerators[topo],
     Function[generator,
      Lookup[generator, "type", "missing"] === "time" ||
       Lookup[topo, "ibpMode", "full"] === "full"
      ]
     ];
   rawTemplates = Table[
     <|"generatorData" -> generator, "generator" -> dsTemplateGeneratorLabel[generator],
       "ibpClass" -> dsTemplateGeneratorClass[generator],
       "expression" -> If[
         Lookup[generator, "type", "missing"] === "time",
         applyTimeGeneratorSeed[topo, base, generator],
         applyMomentumGeneratorSeed[topo, base, generator]
         ]|>,
     {generator, generators}
     ];
   If[MemberQ[Lookup[rawTemplates, "expression", {}], $Failed],
    Return[<|"status" -> "failed", "reason" -> "generatorTemplateFailed"|>]
    ];
   shrunkLines = Lookup[topo, "sectorShrunkLines", {}];
   sectorKey = sectorKeyFromShrunkLines[shrunkLines];
   metadata = Lookup[topo, "sectorMetadata", makeSectorMetadata[topo]];
   representation = If[
     Lookup[topo, "ibpMode", "full"] === "timeOnly",
     "J[timePowers,linePacks,isp]",
     "J[timePowers,indexedLinePacks,isp]"
     ];
   records = Flatten[
     Table[
      Module[{expr = applySeedCanonical[template["expression"] /. discreteRule, topo]},
       <|
        "source" -> dsTemplateSource[sectorKey, template["ibpClass"], shrunkLines],
        "sectorKey" -> sectorKey,
        "sectorShrunkLines" -> shrunkLines,
        "sectorMetadata" -> metadata,
        "generator" -> template["generator"],
        "ibpClass" -> template["ibpClass"],
        "continuousIndices" -> continuousIndices,
        "discreteVariables" -> discreteVariables,
        "discreteRules" -> discreteRule,
        "discreteStateCountExpected" -> 2^Length[discreteVariables],
        "equation" -> Expand[expr],
        "forbiddenNData" -> forbiddenNData[topo, expr],
        "eomCanonicalQ" -> ! containsForbiddenNQ[topo, expr],
        "representation" -> representation,
        "ibpMode" -> Lookup[topo, "ibpMode", "full"]
        |>
       ],
      {template, rawTemplates}, {discreteRule, discreteData["rules"]}
      ],
     1
     ];
   <|
    "status" -> "generated",
    "sectorKey" -> sectorKey,
    "recordCount" -> Length[records],
    "discreteVariables" -> discreteVariables,
    "discreteStateCount" -> Length[discreteData["rules"]],
    "allSeeds" -> records
    |>
   ];


dsLoopSeedTemplateData[context_Association, seedData_Association] := Module[
   {rootTopo, metadataList, shrunkLists, topologies, pieces, bad, records},
   rootTopo = context["topology"];
   metadataList = Lookup[seedData, "sectorMetadataList", {makeSectorMetadata[rootTopo]}];
   shrunkLists = DeleteCases[Lookup[metadataList, "sectorShrunkLines", {}], {}];
   topologies = Join[{rootTopo}, shrinkSectorTopology[rootTopo, #] & /@ shrunkLists];
   pieces = dsLoopTemplatesForTopology /@ topologies;
   bad = Select[pieces, Lookup[#, "status", "failed"] =!= "generated" &];
   If[bad =!= {}, Return[<|"status" -> "failed", "reason" -> "sectorTemplateFailed", "failures" -> bad|>]];
   records = Flatten[Lookup[pieces, "allSeeds", {}], Infinity];
   <|"status" -> "generated", "allSeeds" -> records, "sectorCount" -> Length[pieces],
     "templateCount" -> Length[records]|>
   ];


(* direct pure-time 表示中的 binary h 状态由 treeMasterList 完整枚举；只有顶点 a 指标
   保持 general。该路线与 loop line-pack 模板共享同一个 DSGenerateIBP 接口。 *)
dsPureTimeSeedTemplateData[context_Association] := Module[
   {familyContext, families, records},
   familyContext = dsTreeFamilyContext[context];
   If[familyContext === $Failed, Return[<|"status" -> "failed", "reason" -> "treeFamilyInitializationFailed"|>]];
   families = familyContext["families"];
   records = Flatten@Table[
      Module[{aVariables = a /@ family["vertexOrder"], treeIntegrals},
       treeIntegrals = treeMasterList[family, aVariables];
       Table[
        Module[{record = dsDirectTreeSeedRecord[vertexId, int, family, familyContext]},
         If[Lookup[record, "status", "failed"] =!= "generated", Return[record]];
         Join[record, <|
           "source" -> If[family["sector"] === "top", "time", {"shrinkSectorTime", Lookup[family["topology"], "sectorShrunkLines", {}]}],
           "ibpClass" -> "tIBP",
           "continuousIndices" -> aVariables,
           "discreteVariables" -> {},
           "discreteRules" -> {},
           "discreteStateCountExpected" -> 2^Total[Lookup[family["vertices"], "p", 0]],
           "equation" -> record["treeSeed"],
           "eomCanonicalQ" -> True,
           "forbiddenNData" -> {},
           "representation" -> "J[vertexPacks]",
           "ibpMode" -> "timeOnly",
           "sectorMetadata" -> makeSectorMetadata[family["topology"]]
           |>]
         ],
        {vertexId, family["vertexOrder"]}, {int, treeIntegrals}
        ]
       ],
      {family, families}
      ];
   If[AnyTrue[records, Lookup[#, "status", "generated"] =!= "generated" &],
    Return[<|"status" -> "failed", "reason" -> "directPureTimeTemplateFailed", "records" -> records|>]
    ];
   <|"status" -> "generated", "allSeeds" -> Flatten[records, Infinity],
     "sectorCount" -> Length[families], "templateCount" -> Length[Flatten[records, Infinity]]|>
   ];


makeAllSeedTemplateData[context_Association, seedData_Association] := If[
   Lookup[seedData, "representation", None] === "J[vertexPacks]",
   dsPureTimeSeedTemplateData[context],
   dsLoopSeedTemplateData[context, seedData]
   ];


dsSeedTemplateHashPayload[records_List] := KeyDrop[
    #,
    {"templateSetHash", "templateOrdinal", "templateCount", "contextInputHash", "caseName"}
    ] & /@ records;


dsSealSeedTemplates[records_List, context_Association] := Module[{flat, payload, hash, count},
   flat = Flatten[records, Infinity];
   count = Length[flat];
   payload = dsSeedTemplateHashPayload[flat];
   hash = IntegerString[Hash[payload, "SHA256"], 16, 64];
   MapIndexed[
    Join[#1, <|"templateSetHash" -> hash, "templateOrdinal" -> First[#2],
       "templateCount" -> count, "contextInputHash" -> context["inputHash"],
       "caseName" -> context["caseName"]|>] &,
    flat
    ]
   ];


DSAllSeeds[seedData_Association] := Module[{seeds = Lookup[seedData, "allSeeds", Missing["NotFound"]]},
   If[! ListQ[seeds], Message[DSAllSeeds::badseed]; dsErrorPrint[
      "输入中没有可用的 allSeeds。 No usable allSeeds field was found in the input."
      ]; Return[$Failed]];
   seeds
   ];


DSAllSeeds[] := If[
   ListQ[$dSIBPLastSeedTemplates],
   $dSIBPLastSeedTemplates,
   Message[DSAllSeeds::noseeds];
   dsErrorPrint["尚无 seed 模板。 No seed templates have been generated."];
   $Failed
   ];


(* ::Chapter:: *)
(*连续指标提取与范围门禁*)

DSGenerateIBP::badseeds = "seeds 必须是 DSSeeds 生成的模板列表或含 J 的表达式列表。 seeds must be a template list generated by DSSeeds or a list of expressions containing J.";
DSGenerateIBP::badrange = "撒点范围格式或整数边界无效：`1`。 The sampling range format or integer bounds are invalid: `1`.";
DSGenerateIBP::coverage = "精细范围没有精确覆盖模板指标：`1`。 Detailed ranges do not exactly cover the template indices: `1`.";
DSGenerateIBP::discrete = "n_i 是已在模板阶段遍历的离散指标，不得再次撒点：`1`。 n_i are discrete indices already enumerated in the template stage and must not be sampled again: `1`.";
DSGenerateIBP::symbolicn = "模板仍含符号 n_i，说明离散态/EOM 阶段未完成：`1`。 Symbolic n_i remain in the templates, so discrete-state enumeration or EOM canonicalization is incomplete: `1`.";
DSGenerateIBP::integrity = "seed 模板完整性检查失败：`1`。 Seed-template integrity validation failed: `1`.";
Options[DSGenerateIBP] = {ProgressReporting -> Automatic};
Options[generateIBP] = Options[DSGenerateIBP];


dsSeedTemplateEntries[seeds_] := Flatten[{seeds}, Infinity];


dsSeedTemplateEquation[entry_Association] := Lookup[entry, "equation", Lookup[entry, "treeSeed", Missing["NoEquation"]]];
dsSeedTemplateEquation[entry_] := entry;


dsContinuousIndicesFromIntegral[J[aList_, linePacks_, ispList_]] := DeleteDuplicates@Join[
    Quiet@Check[Variables[Flatten[{aList}]], Cases[aList, _a, Infinity]],
    DeleteDuplicates[Cases[linePacks, _b | _bS, Infinity]],
    Quiet@Check[Variables[Flatten[{ispList}]], Flatten[{ispList}]]
    ];
dsContinuousIndicesFromIntegral[J[vertexPacks_]] := Quiet@Check[
   Variables[First /@ vertexPacks],
   DeleteDuplicates[Cases[vertexPacks, _a, Infinity]]
   ];


dsSeedTemplateContinuousIndices[entries_List] := Module[{declared, inferred},
   declared = DeleteDuplicates@Flatten[Lookup[Select[entries, AssociationQ], "continuousIndices", {}], Infinity];
   inferred = DeleteDuplicates@Flatten[
      dsContinuousIndicesFromIntegral /@ DeleteDuplicates[Cases[dsSeedTemplateEquation /@ entries, _J, Infinity]],
      Infinity
      ];
   DeleteDuplicates@Join[declared, inferred]
   ];


dsSeedTemplateSymbolicN[entries_List] := DeleteDuplicates[Cases[dsSeedTemplateEquation /@ entries, _n, Infinity]];


dsSeedTemplateIntegrityAudit[entries_List] := Module[
   {records, hashes, counts, ordinals, expectedHash, payload, actualHash},
   records = Select[entries, AssociationQ];
   If[Length[records] =!= Length[entries],
    Return[<|"status" -> "unsealed", "passQ" -> False, "reason" -> "rawExpressions"|>]
    ];
   hashes = DeleteDuplicates[Lookup[records, "templateSetHash", Missing["MissingHash"]]];
   counts = DeleteDuplicates[Lookup[records, "templateCount", Missing["MissingCount"]]];
   ordinals = Lookup[records, "templateOrdinal", Missing["MissingOrdinal"]];
   If[Length[hashes] =!= 1 || Length[counts] =!= 1 || First[counts] =!= Length[records] ||
     ordinals =!= Range[Length[records]],
    Return[<|"status" -> "failed", "passQ" -> False, "reason" -> "metadataMismatch",
      "hashes" -> hashes, "counts" -> counts, "ordinals" -> ordinals|>]
   ];
   expectedHash = First[hashes];
   payload = dsSeedTemplateHashPayload[records];
   actualHash = IntegerString[Hash[payload, "SHA256"], 16, 64];
   <|"status" -> If[expectedHash === actualHash, "passed", "failed"],
     "passQ" -> TrueQ[expectedHash === actualHash], "expectedHash" -> expectedHash,
     "actualHash" -> actualHash, "templateCount" -> Length[records]|>
   ];


dsRangePairQ[spec_] := MatchQ[spec, {_Integer, _Integer}] && spec[[1]] <= spec[[2]];


dsRangeSpecificationAudit[indices_List, specs_List] := Module[
   {uniformQ, detailedQ, variables, duplicate, unknown, missing, discrete, invalid},
   uniformQ = Length[specs] === 1 && dsRangePairQ[First[specs]];
   detailedQ = specs =!= {} && And @@ (MatchQ[#, {_, _Integer, _Integer}] & /@ specs);
   If[uniformQ,
    Return[<|"status" -> "passed", "mode" -> "uniform", "variables" -> indices,
      "rangeRules" -> Thread[indices -> ConstantArray[First[specs], Length[indices]]],
      "unknownIndices" -> {}, "missingIndices" -> {}, "duplicateIndices" -> {},
      "discreteIndicesInRangeSpec" -> {}, "invalidRanges" -> {}|>]
    ];
   If[! detailedQ,
    Return[<|"status" -> "failed", "reason" -> "invalidRangeShape", "invalidRanges" -> specs|>]
    ];
   variables = First /@ specs;
   duplicate = Cases[Tally[variables], {var_, count_} /; count > 1 :> var];
   discrete = Select[variables, MatchQ[#, _n] &];
   unknown = Select[variables, Function[var, ! AnyTrue[indices, SameQ[#, var] &] && ! MatchQ[var, _n]]];
   missing = Select[indices, Function[var, ! AnyTrue[variables, SameQ[#, var] &]]];
   invalid = Select[specs, #[[2]] > #[[3]] &];
   <|
    "status" -> If[Join[duplicate, discrete, unknown, missing, invalid] === {}, "passed", "failed"],
    "mode" -> "detailed",
    "variables" -> indices,
    "rangeRules" -> If[Join[duplicate, discrete, unknown, missing, invalid] === {},
      (#[[1]] -> #[[2 ;; 3]]) & /@ specs, {}],
    "unknownIndices" -> unknown,
    "missingIndices" -> missing,
    "duplicateIndices" -> duplicate,
    "discreteIndicesInRangeSpec" -> discrete,
    "invalidRanges" -> invalid
    |>
   ];


(* ::Chapter:: *)
(*公开连续撒点入口*)

dsGeneratedIBPSectorSummaries[records_List] := Module[{sectorKeys},
   sectorKeys = DeleteCases[DeleteDuplicates[Lookup[records, "sectorKey", {}]], "top"];
   Table[
    With[{sectorRecords = Select[records, Lookup[#, "sectorKey", None] === sectorKey &]},
     <|
      "sectorKey" -> sectorKey,
      "sectorShrunkLines" -> Lookup[First[sectorRecords], "sectorShrunkLines", {}],
      "momentumSummary" -> <|"generators" -> DeleteDuplicates[Lookup[Select[sectorRecords, Lookup[#, "ibpClass", None] === "qIBP" &], "generator", {}]]|>,
      "timeSummary" -> <|"generators" -> DeleteDuplicates[Lookup[Select[sectorRecords, Lookup[#, "ibpClass", None] === "tIBP" &], "generator", {}]]|>
      |>
     ],
    {sectorKey, sectorKeys}
    ]
   ];


dsGeneratedIBPBatch[records_List, templates_List, context_Association, rangeAudit_Association,
   integrityAudit_Association] := Module[
   {topRecords, metadataList, forbidden, eomQ, representation, ibpMode, templateHash},
   topRecords = Select[records, Lookup[#, "sectorKey", None] === "top" &];
   metadataList = DeleteDuplicates[Lookup[templates, "sectorMetadata", {}]];
   If[metadataList === {}, metadataList = {makeSectorMetadata[context["topology"]]}];
   forbidden = DeleteCases[Flatten[Lookup[records, "forbiddenNData", {}]], Null];
   eomQ = And @@ Lookup[records, "eomCanonicalQ", {False}];
   representation = Lookup[First[templates], "representation", "J[timePowers,indexedLinePacks,isp]"];
   ibpMode = Lookup[First[templates], "ibpMode", "full"];
   templateHash = Lookup[First[templates], "templateSetHash", Missing["UnsealedTemplates"]];
   <|
    "status" -> "generated",
    "dSIBPStatus" -> "generated",
    "generationRoute" -> "DSGenerateIBP",
    "caseName" -> context["caseName"],
    "ibpMode" -> ibpMode,
    "representation" -> representation,
    "topologyValidationReport" -> topologyValidationReport[context["topology"]],
    "sectorMetadata" -> First[metadataList],
    "sectorMetadataList" -> metadataList,
    "momentumSummary" -> <|"generators" -> DeleteDuplicates[Lookup[Select[topRecords, Lookup[#, "ibpClass", None] === "qIBP" &], "generator", {}]]|>,
    "timeSummary" -> <|"generators" -> DeleteDuplicates[Lookup[Select[topRecords, Lookup[#, "ibpClass", None] === "tIBP" &], "generator", {}]]|>,
    "shrinkSectorSummary" -> <|"sectorSummaries" -> dsGeneratedIBPSectorSummaries[records]|>,
    "equationCount" -> Length[records],
    "eomCanonicalQ" -> eomQ,
    "forbiddenNData" -> forbidden,
    "pendingFeatures" -> {},
    "completeMomentumIBPQ" -> TrueQ[ibpMode === "full"],
    "completeTimeIBPQ" -> True,
    "completeCanonicalQ" -> TrueQ[eomQ && forbidden === {}],
    "allSeeds" -> templates,
    "templateSetHash" -> templateHash,
    "templateIntegrityAudit" -> integrityAudit,
    "continuousIndices" -> rangeAudit["variables"],
    "rangeMode" -> rangeAudit["mode"],
    "rangeRules" -> rangeAudit["rangeRules"],
    "equations" -> records,
    "dSIBPContextSummary" -> dsContextSummary[context],
    "numericRulesAppliedBeforeSeeds" -> False,
    "seedNumericRules" -> {}
    |>
   ];


DSGenerateIBP[seeds_, specs__List, OptionsPattern[]] := Module[
   {entries, badEntries, indices, symbolicN, audit, integrity, context, hashes,
    valueLists, pointRules, progress, records, expression, updated},
   entries = dsSeedTemplateEntries[seeds];
   (* EOM/canonical 可以把某个完整离散态模板化为精确零；密封模板中的 0 仍是合法恒等式。
      非零且不含 J 的表达式继续拒绝，避免把任意常数列表误当作 IBP 模板。 *)
   badEntries = Select[
     entries,
     Function[entry,
      With[{equation = dsSeedTemplateEquation[entry]},
       Head[equation] === Missing || (! TrueQ[equation === 0] && FreeQ[equation, _J])
       ]
      ]
     ];
   If[entries === {} || badEntries =!= {},
    Message[DSGenerateIBP::badseeds];
    dsErrorPrint["seeds 不是可展开的 IBP 模板列表。 seeds is not an expandable IBP-template list."];
    Return[<|"status" -> "failed", "reason" -> "invalidSeeds", "invalidEntries" -> badEntries|>]
    ];
   symbolicN = dsSeedTemplateSymbolicN[entries];
   If[symbolicN =!= {},
    Message[DSGenerateIBP::symbolicn, symbolicN];
    dsErrorPrint["模板必须先完整遍历 n_i=0,1 并执行 EOM。 Templates must enumerate n_i=0,1 and apply EOM first."];
    Return[<|"status" -> "failed", "reason" -> "symbolicDiscreteIndices", "symbolicDiscreteIndices" -> symbolicN|>]
    ];
   indices = dsSeedTemplateContinuousIndices[entries];
   audit = dsRangeSpecificationAudit[indices, {specs}];
   If[Lookup[audit, "discreteIndicesInRangeSpec", {}] =!= {},
    Message[DSGenerateIBP::discrete, audit["discreteIndicesInRangeSpec"]];
    dsErrorPrint["n_i 不属于连续撒点范围。 n_i are not continuous sampling indices."];
    Return[Join[audit, <|"status" -> "failed", "reason" -> "discreteIndexInRangeSpec"|>]]
    ];
   If[Lookup[audit, "status", "failed"] =!= "passed",
    If[Lookup[audit, "reason", None] === "invalidRangeShape",
     Message[DSGenerateIBP::badrange, Lookup[audit, "invalidRanges", {specs}]],
     Message[DSGenerateIBP::coverage, KeyTake[audit, {"unknownIndices", "missingIndices", "duplicateIndices", "invalidRanges"}]]
     ];
    dsErrorPrint["请修正范围格式并完整覆盖所有连续指标。 Correct the ranges and cover every continuous index exactly once."];
    Return[Join[audit, <|"status" -> "failed", "reason" -> Lookup[audit, "reason", "rangeCoverageFailed"]|>]]
    ];
   integrity = dsSeedTemplateIntegrityAudit[entries];
   If[AssociationQ[First[entries]] && ! TrueQ[Lookup[integrity, "passQ", False]],
    Message[DSGenerateIBP::integrity, integrity];
    dsErrorPrint["模板集合被删改或不完整。 The template set was modified or is incomplete."];
    Return[<|"status" -> "failed", "reason" -> "templateIntegrityFailed", "templateIntegrityAudit" -> integrity|>]
    ];
   context = dsResolveContext[Automatic];
   hashes = DeleteDuplicates[Lookup[Select[entries, AssociationQ], "contextInputHash", {}]];
   If[Head[context] === Missing || (hashes =!= {} && hashes =!= {context["inputHash"]}),
    dsErrorPrint["当前 DSInit context 与模板不同源。 The current DSInit context does not match the templates."];
    Return[<|"status" -> "failed", "reason" -> "contextMismatch", "templateContextHashes" -> hashes|>]
   ];
   valueLists = (Range @@ Last[#]) & /@ audit["rangeRules"];
   pointRules = If[indices === {}, {{}}, Thread[indices -> #] & /@ Tuples[valueLists]];
   progress = OptionValue[ProgressReporting];
   records = dsProgressMap[
      "正在展开连续 IBP 指标 / Expanding continuous IBP indices",
      entries,
      Function[entry,
       Table[
        expression = dsSeedTemplateEquation[entry] /. rules;
        expression = If[Lookup[entry, "representation", ""] === "J[vertexPacks]",
          Expand[expression], applySeedCanonical[Expand[expression], context["topology"]]];
        updated = If[AssociationQ[entry], Join[entry, <|
             "continuousRules" -> rules,
             "equation" -> expression,
             "forbiddenNData" -> forbiddenNData[context["topology"], expression],
             "eomCanonicalQ" -> FreeQ[expression, _n]
             |>],
          <|"source" -> "userTemplate", "sectorKey" -> "top", "generator" -> Missing["NotAvailable"],
            "ibpClass" -> "unknownIBP", "continuousRules" -> rules, "equation" -> expression,
            "forbiddenNData" -> {}, "eomCanonicalQ" -> FreeQ[expression, _n]|>];
        If[AssociationQ[entry] && KeyExistsQ[entry, "treeSeed"], updated = Join[updated, <|"treeSeed" -> expression|>]];
        updated,
        {rules, pointRules}
        ]
       ],
      progress
      ] // Flatten[#, 1] &;
   dsInfoPrint[
    "已生成 " <> ToString[Length[records]] <> " 条 IBP 方程。 Generated " <>
     ToString[Length[records]] <> " IBP equations.", progress
    ];
   dsGeneratedIBPBatch[records, entries, context, audit, integrity]
   ];


DSGenerateIBP[seeds_, ___] := (
   Message[DSGenerateIBP::badrange, "expected {min,max} or {index,min,max},..."];
   dsErrorPrint["调用格式应为 {min,max} 或完整的 {index,min,max},...。 Use {min,max} or a complete sequence of {index,min,max},...."];
   <|"status" -> "failed", "reason" -> "invalidCall"|>
   );


generateIBP[args___] := DSGenerateIBP[args];
